### ISSUE TITLE
How can I open the signature window manually?

### ISSUE THREAD

**Issue by NiYanhhhhh** [ray-x/lsp_signature.nvim#101]
Sometimes the signature window is useless and takes too much place, and event cover my code like this:
![image](https://user-images.githubusercontent.com/55988662/133473876-9c3effa5-12dd-4408-96ff-4b507c39cb59.png)
However, at some time I want it open to view the arguments. Therefor, I want the signature window not open by default while I can also use a key to open it manually.
Is it possible or in what way should I setup?
Thanks a lot!

**Comment by ray-x** [comment]
You can config the document lines to zero or use virtual text only mode. Please refer to the ducment.
Also, you can trigger the signature with the key binding to `vim.buf.lsp.signature_help()` in your vimrc in either insert mode and normal mode if you config the floating window to false.
Last, there is another keybind `toggle_key` provided by the plugin.

**Comment by NiYanhhhhh** [comment]
Got it. Thanks again!
