### ISSUE TITLE
Window closes itself with sumneko_lua - close_timeout

### ISSUE THREAD

**Issue by ii14** [ray-x/lsp_signature.nvim#103]
With sumneko_lua the window always closes itself, no matter what, after 4 seconds. clangd doesn't have the same issue.

This is where it happens:

https://github.com/ray-x/lsp_signature.nvim/blob/79fda86596650f21c573b24a2338ce85f19c98aa/lua/lsp_signature.lua#L425-L427

By the way, I think this might be a mistake, the default timeout value is different here:

https://github.com/ray-x/lsp_signature.nvim/blob/79fda86596650f21c573b24a2338ce85f19c98aa/lua/lsp_signature.lua#L29

This option also isn't documented in the README.

My config:

```lua
require 'lsp_signature'.setup {
  bind = true,
  max_width = 80,
  max_height = 12,
  hint_enable = false,
  hint_prefix = '',
  handler_opts = { border = 'none' },
  toggle_key = '<C-K>',
  doc_lines = 2,
  floating_window_above_cur_line = false,
  -- close_timeout = 120000, -- workaround
}
```

Just in case this will be for some reason hard to get right, I propose at least having a way of disabling this timeout, by setting the option to either false, a negative number or zero.

**Comment by ray-x** [comment]
Yes. those setting was for test purpose.
Please refer to latest README
`auto_close_after`

**Comment by ii14** [comment]
Thanks, seems to be working when it's disabled.

I don't see any relevant changes to the actual README, just in the source code.

One thing I'd like to point out, is that I don't think `nil` will actually disable the timeout, you have to set it to `false`:

https://github.com/ray-x/lsp_signature.nvim/blob/5ee2b1fff09463e22679f5f3f8040d1200d6f848/lua/lsp_signature.lua#L41

**Comment by ray-x** [comment]
Please update the code to latest.  The default value updated to nil

**Comment by gegoune** [comment]
It still closes automatically for me even with `auto_close_after = nil` in config.

**Comment by ii14** [comment]
@gegoune Changes are on the "refactor" branch, but `auto_close_after = false` will work if you're on the master branch.

**Comment by ray-x** [comment]
The changes merged to master.
