### ISSUE TITLE
Signature window misplaced when border is set to "none"

### ISSUE THREAD

**Issue by pianocomposer321** [ray-x/lsp_signature.nvim#108]
![signature_window](https://user-images.githubusercontent.com/54072354/134786739-c2ce04c4-ca93-473c-b98b-522e726a31da.png)

When border option is set to "none", the signature window appears several lines above the current line rather then directly above it.

**Comment by zeertzjq** [comment]
This can also sometime happen when `border` is not `none`

**Comment by zeertzjq** [comment]
Now that #109 has been merged, this bug should occur less frequently.
