### ISSUE TITLE
Doesn't work on insert event

### ISSUE THREAD

**Issue by Chaitanyabsprip** [ray-x/lsp_signature.nvim#11]
I installed the plugin this way 
`  use "ray-x/lsp_signature.nvim"`
and my added it to my config as follows
```
local on_attach = function()
  require('completion').on_attach()
  require'virtualtypes'.on_attach()
  require "lsp_signature".on_attach()
end
require'lspconfig'.pyright.setup{on_attach = on_attach}
```

calling `lua vim.lsp.buf.signature_help()` does give proper output
calling `lua require'lsp_signature'.signature()` also gives proper output

**Comment by ray-x** [comment]
I hate `pyright` 😡. Today I did 3 fixes for pyright and merge 1 PR (bugfix) for pyright. I don't understand why the `pyright` behaves so differently compared to other lsp.
Can you check if the latest version works for you?

**Comment by Chaitanyabsprip** [comment]
so, I checked, it is working for java and dart, it is not working for sumeko_lua because I have efm setup with it and it is not working with pyright. 
I used the latest version while checking for these LSPs.

**Comment by ray-x** [comment]
sumeko_lua + efm are for lua code,
I do not think you can have sumeko_lua + efm + pyright at the same time.
If you edit python, only efm+pyright,  if you edit lua, sumeko+efm. Which combination you are using and have issue?

**Comment by ray-x** [comment]
Verified with the following setup. Edited some python and lua code and seems works as expected.

```lua

call plug#begin('~/.vim/plugged')

set noswapfile

Plug 'neovim/nvim-lspconfig'
Plug 'ray-x/lsp_signature.nvim'

call plug#end()

lua <<EOF
local nvim_lsp = require('lspconfig')

require'lspconfig'.pyright.setup {}
require "lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            lua = {
                {formatCommand = "lua-format -i", formatStdin = true}
            },
            python = {
                {formatCommand = "python-flake8 -i", formatStdin = true}
            }
        }
    }
}
local sumneko_root_path = vim.fn.expand("$HOME")..'/github/sumneko/lua-language-server'
local sumneko_binary = vim.fn.expand("$HOME")..'/github/sumneko/lua-language-server/bin/macOS/lua-language-server'


local lua_cfg = {
  cmd = {sumneko_binary, "-E", sumneko_root_path .. "/main.lua"},
  settings = {
    Lua = {
      runtime = {
        -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
        version = "LuaJIT",
        -- Setup your lua path
        path = vim.split(package.path, ";")
      },
      diagnostics = {
        enable = true,
        -- Get the language server to recognize the `vim` global
        globals = {
          "vim",
          "describe",
          "it",
          "before_each",
          "after_each",
          "teardown",
          "pending"
        }
      },
      workspace = {
        -- Make the server aware of Neovim runtime files
        library = {
          [vim.fn.expand("$VIMRUNTIME/lua")] = true,
          [vim.fn.expand("$VIMRUNTIME/lua/vim")] = true,
          [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true
          -- [vim.fn.expand("~/repos/nvim/lua")] = true
        }
      }
    }
  }
}
require'lspconfig'.sumneko_lua.setup (lua_cfg)


require"lsp_signature".on_attach()
EOF


```

**Comment by Chaitanyabsprip** [comment]
> sumeko_lua + efm are for lua code,
> I do not think you can have sumeko_lua + efm + pyright at the same time.
> If you edit python, only efm+pyright will be active, if you edit lua, sumeko+efm. Which combination you are using and have issue?

For lua I am using efm+sumneko_lua and seperately I am using pyright, It is not working for both of them. Let me check with your config and i'll let you know.

**Comment by Chaitanyabsprip** [comment]
I tried with your script and it is working. For some reason it is not working with my setup. I will debug and let you know what I find out.

**Comment by Chaitanyabsprip** [comment]
I dont know what I changed in my config, but it has started working since last night. Thank you for helping through the debugging
