### ISSUE TITLE
Is it possible to trigger the floating window for selection in popup menu?

### ISSUE THREAD

**Issue by heygarrett** [ray-x/lsp_signature.nvim#112]
I'm currently experimenting with using omni completion instead of a dedicated completion plugin, but one thing I'm missing is function signatures for selected completions. Here's what it looks like with nvim-cmp:
<img width="563" alt="Screen Shot 2021-10-06 at 12 53 28" src="https://user-images.githubusercontent.com/1154912/136253915-3e2236b5-6e62-4c2f-ba8f-1cfd2a916c75.png">

Is there a way to trigger the floating window in lsp_signature for selected completions using omni completion?
<img width="563" alt="Screen Shot 2021-10-06 at 12 54 32" src="https://user-images.githubusercontent.com/1154912/136253807-45d3c25e-0355-4f09-9426-6a44ec545f58.png">

**Comment by ray-x** [comment]
The signature has to be triggered inside the function and after trigger character (e.g. `(`, `,`)

**Comment by heygarrett** [comment]
That's what I though, but I figured it would be worth asking anyway. Thanks!
