### ISSUE TITLE
[feature request] xml doc string

### ISSUE THREAD

**Issue by quantum-booty** [ray-x/lsp_signature.nvim#113]
![image](https://user-images.githubusercontent.com/28958399/137586628-81eee7b6-06b6-4835-81d3-0e1fcd99cca9.png)
Would be nice to parse this and present it in a more readable format.

**Comment by quantum-booty** [comment]
Edit: this is the c# Rosalyn language server.

**Comment by ray-x** [comment]
@AnonymusRaccoon 
Thanks!

**Comment by AnonymusRaccoon** [comment]
I think this issue can be closed, since it has been fixed on omnisharp. This is what it looks like with a nightly build: 
![image](https://user-images.githubusercontent.com/32224410/166154209-6386282e-f463-4800-ac86-3d08b265cb94.png)

**Comment by ray-x** [comment]
Thanks! @AnonymusRaccoon
