### ISSUE TITLE
hide popup documentation

### ISSUE THREAD

**Issue by siduck** [ray-x/lsp_signature.nvim#115]
![image](https://user-images.githubusercontent.com/59060246/138198460-31d6a5ae-cf40-48a5-83b0-31eec2ede845.png)

is it possible to just show args rather than the whole docs?

something like this  :

![image](https://user-images.githubusercontent.com/59060246/138198247-da234909-c9d2-4d35-ad59-09dd8becd8a6.png)

**Comment by ray-x** [comment]
You can set `doc_lines` to a smaller number. set it to 0 to disable the document being shown.

**Comment by ajitid** [comment]
Hey @ray-x , just on this, `doc_lines`  can't be used for normal mode. Is this due to some limitation?
