### ISSUE TITLE
Persistent toggle

### ISSUE THREAD

**Issue by DEliasVCruz** [ray-x/lsp_signature.nvim#118]
with this config, which i attach in the lsp `on_attach` function:

```lua
require("lsp_signature").on_attach {
    bind = true,
    doc_lines = 2,
    floating_window = true,
    hint_enable = false,
    use_lspsaga = false,
    hi_parameter = "Search",
    max_height = 12,
    max_width = 150,
    fix_pos = false,
    handler_opts = {
      border = "single",
    },
    always_trigger = false,
    toggle_key = "<C-s>",
  }
```

With this I would expect that the floating window would only appear when I
press `<C-s>` and remain there until I either hit `<C-e>` again or leave insert
mode

Effectively I would expect that I could get a persistent signature help when on
insert mode **on demand**

But the actual behavior is that the floating window appears always and only
gets toggle off when I hit `<C-e>` and is toggle back on once I hit `<space>`.
If this is intended behavior **how could I achieve the behavior I expect**

**Comment by snorkysnark** [comment]
Why is this closed? Did you find a solution?
