### ISSUE TITLE
Autocompletion toggles off after showing it

### ISSUE THREAD

**Issue by romariolopezc** [ray-x/lsp_signature.nvim#119]
Hello, I just migrated from `nvim-compe` to `nvim-cmp` and I'm seeing a weird behaviour when autocompleting a function:

![nvim-lsp_signature](https://user-images.githubusercontent.com/6199588/138579575-594e8c03-931b-4ce7-b9f8-5dde2758a28c.gif)

Like in the video, it toggles off when autocompleting after some milliseconds

**Comment by kraem** [comment]
I've found that this bug happens with
- https://github.com/L3MON4D3/LuaSnip
- https://github.com/dcampos/nvim-snippy

but not with https://github.com/hrsh7th/vim-vsnip

**Comment by ray-x** [comment]
I would recommend luasnip

**Comment by danymat** [comment]
What's the state of this bug? I too get the bug with LuaSnip

**Comment by ray-x** [comment]
I am using LuaSnip+CMP, but did not see the same issue.
Would be great someone can share a minium vimrc that can reproduce this issue.

**Comment by and3rson** [comment]
I could also reproduce this with `LuaSnip`. I've switched to `snippy` and the disappearing is gone - the popup shows perfectly.

**Comment by Mikkolehtimaki** [comment]
I'm seeing this issue if I accept snippet completion from nvim-cmp. I'm using vsnips. The signature window disappears until you start typing again. It also disappears if you move to next function argument using snippets. No issues when not accepting snippet completions.

**Comment by ZenLian** [comment]
I've met the same issue with cmp, luasnip and nvim-autopairs enabled.

environments:

- WSL-Ubuntu20.04
- nvim-v0.5.1

This is a minimal `init.lua` file which can reproduce this issue.

```lua
local fn = vim.fn
local packer_dir = fn.stdpath('data') .. '/site/pack/packer/opt/packer.nvim'

if fn.empty(fn.glob(packer_dir)) > 0 then
    packer_bootstrap = fn.system {'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', packer_dir}
end

vim.cmd [[packadd packer.nvim]]
packer = require('packer')
packer.startup({
    function()
        use {'wbthomason/packer.nvim', opt = true}

        use {'neovim/nvim-lspconfig'}
        use {'williamboman/nvim-lsp-installer'}

        use {'ray-x/lsp_signature.nvim'}

        use {'hrsh7th/nvim-cmp'}
        use {'hrsh7th/cmp-nvim-lsp'}

        use {'L3MON4D3/LuaSnip'}
        use {'saadparwaiz1/cmp_luasnip'}

        use {'windwp/nvim-autopairs'}
    end,
    config = {
        display = {
            open_fn = function()
                return require("packer.util").float({border = "single"})
            end
        }
    }
})

if packer_bootstrap then
    packer.sync()
end

local on_attach = function(client, bufnr)
    -- other settings removed
    -- lsp_signature
    require("lsp_signature").on_attach()
end

local lsp_installer = require("nvim-lsp-installer")
lsp_installer.on_server_ready(function(server)
    local opts = {
        on_attach = on_attach,
        flags = {
            debounce_text_changes = 150
        }
    }
    if server.name == 'sumneko_lua' then
        opts.settings = {
            Lua = {
                diagnostics = {
                    -- Get the language server to recognize the `vim` global
                    globals = {'vim'},
                },
                workspace = {
                    -- Make the server aware of Neovim runtime files
                    library = vim.api.nvim_get_runtime_file("", true),
                },
                -- Do not send telemetry data containing a randomized but unique identifier
                telemetry = {
                    enable = false,
                },
            }
        }
    end
    server:setup(opts)
end)

-- cmp configs --
local has_words_before = function()
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and
        vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end


local cmp = require('cmp')
cmp.setup {
    mapping = {
        ["<CR>"] = cmp.mapping.confirm({select = true}),
        ["<C-p>"] = cmp.mapping.select_prev_item(),
        ["<C-n>"] = cmp.mapping.select_next_item(),
        ["<C-d>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        ["<C-e>"] = cmp.mapping.close(),
        ["<Tab>"] = cmp.mapping(
            function(fallback)
                if cmp.visible() then
                    cmp.select_next_item()
                elseif require('luasnip').expand_or_jumpable() then
                    require('luasnip').expand_or_jump()
                elseif has_words_before() then
                    cmp.complete()
                else
                    fallback()
                end
            end,
            {"i", "s"}
        ),
        ["<S-Tab>"] = cmp.mapping(
            function(fallback)
                if cmp.visible() then
                    cmp.select_prev_item()
                elseif require('luasnip').jumpable(-1) then
                    require('luasnip').jump(-1)
                else
                    fallback()
                end
            end,
            {"i", "s"}
        ),
    },
    snippet = {
        expand = function(args)
            require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        end,
    },
    sources = {
        { name = 'nvim_lsp' },
        { name = 'luasnip' },
    },
    completion = {
        completeopt = 'menu,menuone,noinsert'
    },
    experimental = {
        ghost_text = true
    }
}


require("luasnip").config.set_config {
    history = true,
    updateevents = "TextChanged,TextChangedI"
}
require("luasnip.loaders.from_vscode").load()


require('nvim-autopairs').setup()
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp = require('cmp')
cmp.event:on( 'confirm_done', cmp_autopairs.on_confirm_done({  map_char = { tex = '' } }))
cmp_autopairs.lisp[#cmp_autopairs.lisp+1] = "racket"
```

**Comment by ray-x** [comment]
@ZenLian 
Please check if this comment helps
https://github.com/ray-x/lsp_signature.nvim/issues/128#issuecomment-974790499

**Comment by ray-x** [comment]
Also please not that signature help only pop up in insert mode.
In Normal mode, you have to manual trigger the signature help with key binding to lsp.signature_help()

**Comment by ZenLian** [comment]
@ray-x Sorry I didn't response in time.

It seems that `nvim-autopairs` has some conflicts with this plugin, but I don't know how to resolve it.

I've tried to delete this line:

```lua
cmp_autopairs.lisp[#cmp_autopairs.lisp+1] = "racket"
```

but it doesn't help.

It only works when I delete this line too:

```lua
cmp.event:on( 'confirm_done', cmp_autopairs.on_confirm_done({  map_char = { tex = '' } }))
```

But I can not get `()` inserted after selecting function without this line above.

I've checked your vimrc repository and found you have this line too, which makes me confused.

**Comment by ray-x** [comment]
I have been using autopairs and cmp for a time. And have never seen this issue.
I tried your init.lua. But for some reason, I am not able to see the issue as well.

**Comment by ray-x** [comment]
Submitted a bugfix. not sure if it will work as I do not see this issue normally in my setup.

**Comment by ZenLian** [comment]
It works! Thanks a lot!

**Comment by ray-x** [comment]
@romariolopezc 
Please check if it works for you as well. I will leave it open for a few days unless you still see issue.

**Comment by romariolopezc** [comment]
@ray-x it works! Thanks!! :tada:

**Comment by a-h** [comment]
I had the issue and the updated version works great for me. Thanks ray-x.

For anyone else's reference my config is at https://github.com/a-h/dotfiles

I updated to use the latest version at commit https://github.com/a-h/dotfiles/commit/2c3e8df538d0f584ae9cda52fc4178619d1d1289

**Comment by ray-x** [comment]
Great, thanks for your confirm
Also, thanks for sharing your nix config @a-h
