### ISSUE TITLE
Error when showing signature

### ISSUE THREAD

**Issue by danymat** [ray-x/lsp_signature.nvim#121]
Hello, I updated lsp_signature yesterday and made it unusable with sumneko_lua lsp:

`Error executing vim.schedule lua callback: ...pack/packer/opt/lsp_signature.nvim/lua/lsp_signature.lua:167: attempt to compare number with nil`

**Comment by ray-x** [comment]
I think the issue fixed, if you still seeing this, feel free to reopen
