### ISSUE TITLE
single borders should be non-rounded

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ray-x/lsp_signature.nvim#122]
border type `single` should be appear square by default, but as we can see in [lua_signature_helper.lua](https://github.com/ray-x/lsp_signature.nvim/blob/fddd3f958af06c0239a9b019cb2e180a93cb6a9c/lua/lsp_signature_helper.lua#L435), we are overriding this by a rounded single border. To make this more consistent with other nvim-lua plugins, as well as the internal border spec, this should be square. Users who want rounded corners for a single border can use the rounded option.

**Comment by ray-x** [comment]
thanks, added `rounded`

**Comment by ray-x** [comment]
This should be solved in latest
