### ISSUE TITLE
Popup doesn't close after exiting insert mode

### ISSUE THREAD

**Issue by AgentCosmic** [ray-x/lsp_signature.nvim#123]
As per title, the popup will stay around after I finish editing. I'll have to enter insert mode and exit again to close the popup.

**Comment by ray-x** [comment]
Yes. I also saw this issue. But do not have a way to 100% reproduce this issue.

**Comment by lobre** [comment]
I can only reproduce this when using `<C-c>` to exit insert mode instead of `<Esc>`. Do you have the same behavior?

**Comment by ray-x** [comment]
From the vim doc, <C-c> will not trigger `InsertLeave` event, on which the plugin is listen.
So the behaviour is expected.

**Comment by jonhoo** [comment]
Hmm, that seems very unfortunate. I wonder why `InsertLeave` is _only_ emitted from `<Esc>` and none of the other ways (keymapped or not) to leave insert mode :thinking:
