### ISSUE TITLE
Is zindex actually being used?

### ISSUE THREAD

**Issue by ElPiloto** [ray-x/lsp_signature.nvim#124]
I've tried to set zindex to high values in my config, but it does not seem to be used.  Looking at the code, I can't see where the zindex value is actually used (except once where it's evaluated as a binary (`zindex > 50`)).  It also seems like config isn't used for that and that it takes the (hard-coded?) value from `_LSP_SIG_CFG.zindex`.  But even manually editting `_LSP_SIG_CFG.zindex = 900`, the signature help is still behind nvim-cmp completion popup.

**Comment by ray-x** [comment]
It should be passed into float windows API.

**Comment by ElPiloto** [comment]
Ah, I see. I didn't see this line [here](https://github.com/ray-x/lsp_signature.nvim/blob/600111e6249bcc948e2b811ef09adf4ea84ebfc1/lua/lsp_signature.lua#L529) which merges the default values in _LSP_SIG_CFG with user config.  

I'm still getting clashes with `nvim-cmp` going over `lsp-signature`.  As far as I can tell, [they set their zindex](https://github.com/hrsh7th/nvim-cmp/blob/b185e303bd00390325c582d0366f85298cf84299/lua/cmp/view/custom_entries_view.lua#L158) to 1001, but setting lsp-signature's zindex to higher doesn't change their ordering for me.  Any clues?

**Comment by ray-x** [comment]
@ElPiloto dose it solved?
![image](https://user-images.githubusercontent.com/1681295/142755682-e1dea9f4-cefe-45f9-8ba9-6a00cb738cc2.png)
If I change zindex in lspsignature to 1002 I can see it was not covered

**Comment by ElPiloto** [comment]
Thanks for getting back to me, it must be an issue with my (currently very messy) config somewhere.
