### ISSUE TITLE
Attempt to perform arithmetic on local 'sig_woff' (a nil value)

### ISSUE THREAD

**Issue by sudkumar** [ray-x/lsp_signature.nvim#127]
Looks like line **407** is causing a `nil` value exception for `sig_woff` local var.

https://github.com/ray-x/lsp_signature.nvim/blob/8c051d8d0810e2e5701e72119a73807a03304267/lua/lsp_signature_helper.lua#L395-L409

```
Error executing vim.schedule lua callback:
  ...cker/opt/lsp_signature.nvim/lua/lsp_signature_helper.lua:407: 
  attempt to perform arithmetic on local 'sig_woff' (a nil value)
```

 This was introduced in the commit  (https://github.com/ray-x/lsp_signature.nvim/commit/8c051d8d0810e2e5701e72119a73807a03304267). Maybe we should set a default value here.

```diff
- woff = sig_woff + (#line_to_cursor - woff)
+ woff = (sig_woff or 0) + (#line_to_cursor - woff)
```

**Comment by BeyondMagic** [comment]
Faster than me.

![image](https://user-images.githubusercontent.com/51831435/142338140-1040e3a5-8b6c-4095-97ad-874ac3112798.png)

**Comment by ray-x** [comment]
Thanks. just pushed a fix.

**Comment by sudkumar** [comment]
Working perfectly now. @ray-x Thank you for the quick fix. 🙏
