### ISSUE TITLE
[Error] executing vim.schedule lua callback ... lsp_signature.lua: 257

### ISSUE THREAD

**Issue by af-yamada** [ray-x/lsp_signature.nvim#129]
When I'm editing a scala program. I got a following error message.

> Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:257: attempt to
> index a nil value

I'm using metals as a lsp with a version of 0.10.9. It's prone to appear editing in a quoted sentence.

**Comment by ray-x** [comment]
Could you share 
1) The current line you trying editing
2) the function prototype

I think I may need to take care of the quote

**Comment by af-yamada** [comment]
Thank you for your reply.
1. println(s"   , then I got above message.
2. the function prototype is println(x: Any): Unit

**Comment by ray-x** [comment]
Thanks, what `s"` mean?
What would be the function call, is it something like `println(s"hello")` ?

**Comment by af-yamada** [comment]
Sorry for my poor explanation.
It is String Interpolation in Scala. We can embed a variable into a string such as:
> val name = "John"             <- variable declaration
> println(s"Hello, $name")  <- output: "Hello, John" with a new line.
In the case, 's' is a preceding character showing the following string is String Interpolation.

**Comment by ray-x** [comment]
This is a metals bug
from the log, here is the response from metals

```
{
    activeParameter = 0,
    activeSignature = 1,
    signatures = {{label = "s(args: Any*): String", parameters = {{label = "args: Any*"}}}}
  }

```

activeSignature was set to 1.  The LSP spec shows the index should be 0-based. 1 will be an out of range value means NO signature available.

**Comment by af-yamada** [comment]
I see, zero-based indexing.

Thank you for your report and effort.

**Comment by af-yamada** [comment]
I think you corrected the issue. Thank you ver much.

**Comment by ray-x** [comment]
In fact, I am doing boundary check and try not through error when input is not correct.  But glad it works for you .
