### ISSUE TITLE
How to use this standalone?

### ISSUE THREAD

**Issue by zacmar** [ray-x/lsp_signature.nvim#13]
If I use the built-in signature help
```lua
vim.api.nvim_set_keymap("n", "gk", "<cmd>lua vim.lsp.buf.signature_help()<CR>", {})
```
I see the markdown backticks, however since the built-in signature help doesn't actually render a markdown preview, this is not-so-useful (note the backticks around ("output"):
![2021-04-30-120948_1873x724_scrot](https://user-images.githubusercontent.com/32982619/116681227-fa13c200-a9ac-11eb-8b61-5b6b18e5ee98.png)

If i use lspsaga to render the signature help
```lua
vim.api.nvim_set_keymap("n", "gk", "<cmd>lua require('lspsaga.signaturehelp').signature_help()<CR>", {})
```
I get a nicely rendered markdown help, however I dont see any highlighting of the current parameter:
![2021-04-30-121119_1106x567_scrot](https://user-images.githubusercontent.com/32982619/116681515-5e368600-a9ad-11eb-9772-125a9559df75.png)

How do I use this plugin?

**Comment by zacmar** [comment]
Actually, the build-in hover does render the markdown, however if I add
```lua
require'lsp_signature'.on_attach()
```
anywhere in my `init.lua` it does no longer.

**Comment by ray-x** [comment]
What lsp you are using? pyls?

**Comment by zacmar** [comment]
Exactly.

**Comment by zacmar** [comment]
I don't really understand how the interplay between this plugin, who determines the 'active parameter' and who renders the markdown, but [https://github.com/neovim/neovim/pull/14456](https://github.com/neovim/neovim/pull/14456) exactly describes my problem. But obviously this is not merged, so I don't really understand what is going on here... :smile:

**Comment by ray-x** [comment]
The active parameter was sent back from LSP. I hope Pyls does that correctly.  The markdown was also should rendered by LSP.

**Comment by ray-x** [comment]
I think if you want to use lspsaga, you need to set the bind = false in attach configuration.

**Comment by mjlbach** [comment]
The signature help in neovim should no longer show backticks/etc. Please file an issue if it does (all of our floating windows got unified/beautified by folke)

**Comment by ray-x** [comment]
@zacmar 
This issue should be fixed in the latest version would you check the behaviour?

**Comment by zacmar** [comment]
Works for me using the built-in signature help :+1:, but I cant get it to work with `lspsaga`. I do not see any difference between enabling this plugin or not when using `lspsaga` (both at their respective newest commit). At the moment I'm fine with using the built-in help, which I assume will converge to `lspsaga`-like behavior anyway with the newest changes.

**Comment by ray-x** [comment]
To use lspsaga, you need to set `use_lspsaga = true`. But I am glad you like the build-in one.
