### ISSUE TITLE
doc_lines = 1 doesn't trim extra lines

### ISSUE THREAD

**Issue by Lahvuun** [ray-x/lsp_signature.nvim#130]
![image](https://user-images.githubusercontent.com/6643565/144092491-8a944915-0170-497d-bb4a-f537ee4e568f.png)

**Comment by ray-x** [comment]
A bug fix was pushed

**Comment by Lahvuun** [comment]
82c463e5e639fc61eea7be03a68bea272f828cc1 fixed the issue for me.
Thank you!
