### ISSUE TITLE
Autocompletion float is hidden behind lsp_signature float when cursor is near top of bottom of window

### ISSUE THREAD

**Issue by dmbfm** [ray-x/lsp_signature.nvim#133]
Not really sure if it is a bug at all nor if its an issue with lsp_signature or with the completion plugin.

When I'm writing a function call and the cursor is near the bottom or the top of the vim window the completion flow gets hidden behind the lsp_signature float:

<img width="934" alt="Screen Shot 2021-12-05 at 10 39 15" src="https://user-images.githubusercontent.com/8743306/144748985-a469bc58-9897-444f-9fb8-6ea2f9bbf120.png">

I'm not 100% sure but I think this didn't happen before I updated to neovim v0.6.0.

I'm using lsp_signature trunk and this is the output of `nvim --version`:

```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.0/share/nvim"
```

The completion plugin I'm currently using is [nvim-compe](https://github.com/hrsh7th/nvim-compe).

**Comment by ray-x** [comment]
It is expected behaviour.  compe does not support zindex, and it will be behind lsp_signature
You can adjust zindex of lsp_signature to a smaller value so it will not block compe.

**Comment by dmbfm** [comment]
Got it, thanks! I imagined it was something like that but I didn't know how it worked.
