### ISSUE TITLE
Signature float (sometimes) remains visible after going back to normal mode 

### ISSUE THREAD

**Issue by dmbfm** [ray-x/lsp_signature.nvim#135]
So this is a little tricky to replicate and it only happens sometimes when I'm typing quickly and try to save a file while the signature float is visible.

At first it appeared to be at random, but I was able to replicate it somewhat consistently by doing this: 
- After the signature float appears, start typing the parameter name and navigate through the completion float
- Quickly go back to normal mode and save the file
- You will be in normal mode but the signature float remais visible.

https://user-images.githubusercontent.com/8743306/145075554-419f2c3f-8277-4774-aae5-fb6a0cda1d18.mov

I'm pretty sure this did not happen until I updated to neovim 0.6.0. 

My config:

```
lsp_signature.on_attach {
            extra_trigger_chars = { "(", "," },
            hi_parameter = "IncSearch",
            bind = true,
            handler_opts = {
                -- border = "rounded",
                -- border = "double",
                -- border = "single",
                border = "shadow",
                -- border = "none",
            },
            zindex = 50,
            -- debug = true,
            -- verbose = true,
        }

```

neovim version:
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.0/share/nvim
```

**Comment by ray-x** [comment]
Just to be sure, you are using \<esc> to back to normal mode not \<ctrl-c>

**Comment by dmbfm** [comment]
Yes, just using 'jk' mapped to <ESC>. Also only happens when its done quickly

**Comment by ray-x** [comment]
That might be because of the debounce timer. If you are fast enough, you may avoid the timer and the state machine may be incorrect.  I bet you have a good keyboard 😀.
The current timer setup is 0.3s. It is possible you press 2 keys inside that period, or if you have a keymap that toggles the mode.
Also, save command may trigger multiple autocmd and could be an issue as well.

**Comment by dmbfm** [comment]
I thought it was something like that! 

I guess neovim v0.6.0 must have changed something with the timing of events as this didn't happen before. 

Closing this then, thanks!
