### ISSUE TITLE
Lsp_signature opening between two splits only and can't see the signature.

### ISSUE THREAD

**Issue by dantearaujo1** [ray-x/lsp_signature.nvim#137]
Im using:

NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilado por runneradmin@fv-az152-703

With nvim-cmp, lspsaga, lspkind, nvim-lspconfig all updated, tried using omnisharp server and clangd but i can't see anything from lsp_signature with just one pane. with 2 or more i can only see a parte of the doc text.

 
![image](https://user-images.githubusercontent.com/21104508/145379041-24370f1a-2695-47e2-99a7-e20eb6c7b1e2.png)

**Comment by ray-x** [comment]
That is strange and would be reported by other users as well.
Could you share your minium vimrc?
Also you can check with this vimrc (you may need to add your own lsp setup)

https://github.com/ray-x/lsp_signature.nvim/blob/master/tests/init_paq.lua
