### ISSUE TITLE
highlights

### ISSUE THREAD

**Issue by horseinthesky** [ray-x/lsp_signature.nvim#14]
Is there a way to remove these `\`` when highlighting a parameter?

Also is there a way to change fore/background of the signature since it doesn't really match anything:
![image](https://user-images.githubusercontent.com/19948672/116775238-a23b9080-aa6a-11eb-9b8c-14eb039147e3.png)

As an example here is how Saga diagnostic looks like:
![image](https://user-images.githubusercontent.com/19948672/116775268-dd3dc400-aa6a-11eb-916f-2d603de3e066.png)

**Comment by ray-x** [comment]
You can config the way the current parameter highlight by adding 
decorator = {"**", "**"}.  or whatever you think looks good
in the configure

The highlight is provided by neovim itself. It is hard to change unless the flowing windows re-implemented (e.g. lspsaga)

**Comment by horseinthesky** [comment]
@ray-x I've checked the `decorator` option but it only defines the symbol, not the color.
![image](https://user-images.githubusercontent.com/19948672/116776794-242fb780-aa73-11eb-97c3-dcad65b12467.png)

So am I correct to say `\`` is the only option here?

Regarding fore/background highlighting, do this light foreground and dark background comes from some default floating window settings? No way to change this?

**Comment by ray-x** [comment]
If you want to it be coloured you may need to use backstick

The background is coming from your current colour scheme. I do not know how neovim pick the float window background, but it not controlled by the plugin.  You can change to another scheme that looks less obvious or disable the broader.

**Comment by horseinthesky** [comment]
Ok. Thank you.
