### ISSUE TITLE
Use toggle_key with "floating_window = false"

### ISSUE THREAD

**Issue by vRoussel** [ray-x/lsp_signature.nvim#140]
Not sure if this is intended behavior or a bug. 

If I set floating_window to false, the toggle_key doesn't do anything. What I'm trying to achieve is to have the floating window disabled by default, while having a mapping to toggle it.

I read in another issue that I can achieve that by mapping something to "vim.lsp.buf.signature_help()", but then it's not a toggle since I can only open the floating window with that mapped key, not close it.

**Comment by lougreenwood** [comment]
I think this sounds like what I'm also trying to achieve.

Basically, I would like to use a mapping so that I can get the signature info for a function under the cursor - similar to how VSCode shows signature info.

Is this use case possible or even intended with lip_signature?

**Comment by ray-x** [comment]
FYI would be great to check if the behaviour of latest version works for you.

**Comment by vRoussel** [comment]
That's exactly what I wanted, thank you !
