### ISSUE TITLE
Plugin does not works with nvim_jdtls

### ISSUE THREAD

**Issue by rishabh3** [ray-x/lsp_signature.nvim#141]
I use nvim_jdtls for java integration and tried to use this plugin. I have added the code require'lsp_signature'.on_attach() in jdtls on_attach function, but this plugin always gives the following error.
`Error executing vim.schedule lua callback: ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:221: attempt to index local 'actSig' (a nil value)
stack traceback:
        ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:221: in function 'handler'
        ...l/Cellar/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp.lua:957: in function 'cb'
        vim.lua:285: in function <vim.lua:285>`
I know this plugin does not support nvim_jdtls, but can this be added as enhancement or this is something not feasible?

**Comment by andersevenrud** [comment]
I get a very similar error with omnisharp/mono but only sometimes.

```
Error executing vim.schedule lua callback: ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:221: attempt to index local 'actSig' (a nil value)
stack traceback:
        ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:221: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:964: in function ''
        vim.lua: in function <vim.lua:0>
```

**Comment by ray-x** [comment]
Please check this issue: https://github.com/ray-x/lsp_signature.nvim/issues/97
I think jdtls dose not enable active parameter by default. You need to setup the jdtls to enable it.
As for omnisharp, would you send me the function signature so I can reproduce it? I think it might be incorrect format of omnisharp response. thanks!

**Comment by andersevenrud** [comment]
@ray-x 

I just found a way to reproduce this using C# with UnityEngine.

```cs
using UnityEngine;

public class Node
{
    public Node()
    {
        Debug.Log("Foo",); // <-- Error triggers on the comma
    }
}
```

https://user-images.githubusercontent.com/161548/146690441-1a121a75-7bb4-4d3a-aaf1-45f15affb44d.mp4

If you need any more info let me know.

**Comment by rishabh3** [comment]
Hi @ray-x ,
I did try to go through the issue you had tagged, in your previous comment. What I see is that although I have signature help enabled, I still see the same issue I have reported above when I add the `require'lsp_signature'.on_attach()` call in my jdtls config.
I do get lsp_signature from jdtls and the documentation as well, but it does not work with this plugin.

**Comment by rishabh3** [comment]
Updating the plugin works, seems i was running some old version or something was missing
