### ISSUE TITLE
Feature: A way to view full parameter documentation with binding

### ISSUE THREAD

**Issue by joshpetit** [ray-x/lsp_signature.nvim#146]
Hey! This plugin is awesome! Super useful. I was wondering if it'd be possible to implement something so that we can toggle between showing the full lsp signature window and just the virtual text. This would be useful since sometimes the popup window obscures the cursor, and being able to toggle between the two would be really useful.

Thanks again for this plugin!

**Comment by ray-x** [comment]
Is it similar to issue #140 ?
ATM toggle key will toggle popup floating windows no matter floating window is enabled or not.

**Comment by joshpetit** [comment]
Oh sorry didn't see that, thanks a lot!

**Comment by joshpetit** [comment]
This may be unrelated, but when I map the toggle key to `<C-i>`, I cant seem to insert tabs into my code. When I map it to anythign else it works, is there a reason for this? Im assuming it's neovim related.
