### ISSUE TITLE
Manually trigger

### ISSUE THREAD

**Issue by n0bra1n3r** [ray-x/lsp_signature.nvim#148]
Thanks for creating this plugin!

I'm using `nvim-cmp` with this plugin. At the moment I'm using custom logic to trigger `nvim-cmp`'s autocomplete using the technique described [here](https://github.com/hrsh7th/nvim-cmp#full-managed-completion-behavior). Is there a way to do something similar for `lsp_signature`?

**Comment by ray-x** [comment]
the only way 
1) use manually trigger keymap
2) status_line API and pop up your own floating windows

**Comment by ssipos90** [comment]
@ray-x please detail your response, how can we enable signature on demand only?

I like this plugin a lot, but it's extremly intrusive, I manually close it but gets retriggered like 4 times because of LSP and I'd rather have it open manually, when I need some help with a signature.

**Comment by ray-x** [comment]
If you want a status line hint. Here are some discussion of how we set it up. https://github.com/ray-x/lsp_signature.nvim/issues/160

Also you can setup the floating_window to false to disable the floating_window and use your keymap to `lua vim.lsp.buf.signature_help()` to trigger the helper.

**Comment by ssipos90** [comment]
thanks!
