### ISSUE TITLE
Signature help keeps opening after toggle close

### ISSUE THREAD

**Issue by drusmanbashir** [ray-x/lsp_signature.nvim#157]
Hi,
Thank you for this great plugin. My issue is that once I've seen the signature help, I want the helpbox to close so I may focus on the code. I press the toggle key (Alt-x) and it closes, but reopens as soon as i type another letter. Is it possible that it remain closed once you toggle it? Also, is there any way to make the font smaller? 
![Peek 2022-01-13 10-38](https://user-images.githubusercontent.com/5282314/149315353-8923bc9b-113f-442f-ad14-567ea97ec646.gif)
#

**Comment by ray-x** [comment]
Well, that is expected.
You can change to virtual text-only mode by disabling `floating_windows`.
 Also, you can define your own keymap to set  (or, toggle with a function)
`_LSP_SIG_CFG.floating_window = false` so it can be disable for a while.

**Comment by drusmanbashir** [comment]
Thanks Ray-X its an awesome plug-in. Wish you the best!

**Comment by ray-x** [comment]
Cheers!
