### ISSUE TITLE
Is it possible to get signature and hint on hover?

### ISSUE THREAD

**Issue by augustocdias** [ray-x/lsp_signature.nvim#158]
I have configured the plugin to show in the status line as explained in the docs and I was wondering if it is possible to also show the signature on hover in normal mode. Is this somehow possible?

**Comment by ray-x** [comment]
Yes, it is possible,  you can use default mapping from lspconfig
```
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
```

**Comment by augustocdias** [comment]
Nothing happens when I call that function... Was that supposed to open a float window or something? 

I wanted just the status to show

**Comment by ray-x** [comment]
What is mapped to \<c-k> in your system?
it should be `n  <C-K>       *@<Cmd>lua vim.lsp.buf.signature_help()<CR>` when you `nmap <c-k>`

**Comment by augustocdias** [comment]
Yes. Just like you posted. I tried also to call the function manually

**Comment by ray-x** [comment]
Could you post your config?
Also, signature_help function works only at the position between the trigger characters of your language. e.g. between `()`

**Comment by augustocdias** [comment]
Okay... I didn't knot it had to be between the `()`. it works perfectly. Thanks for the help

**Comment by augustocdias** [comment]
One last question: is it possible to not open the float window and just show in the status line?

**Comment by ray-x** [comment]
You can disable floating_windows by setting ` floating_window = false,`
