### ISSUE TITLE
Last active parameters' highlighting not getting cleared

### ISSUE THREAD

**Issue by mbenford** [ray-x/lsp_signature.nvim#159]
When typing function arguments the last active parameters' highlight aren't getting cleared anymore:

![image](https://user-images.githubusercontent.com/446867/150660680-70103790-2ff7-430f-8c85-aa83a0db48b6.png)

I've tracked it down to commit 0b27fb039ab51681649b613d2825a54965f831ec. Up until 724d955915d64713fade35f98b96cf50a45e9f88 it was working correctly:

![image](https://user-images.githubusercontent.com/446867/150660767-fe9036c9-c0b0-4e2d-bfe9-e14e096985d9.png)

**Comment by ray-x** [comment]
Would you send a minium vimrc to reproduce this issue. I do not see the issue in my config.

**Comment by mbenford** [comment]
Sorry for not providing in the first place. I thought the commits themselves would pinpoint the issue. Here you go:

```lua
vim.cmd('packadd packer.nvim')

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'neovim/nvim-lspconfig'
  use {'williamboman/nvim-lsp-installer',
    config = function()
      local installer = require('nvim-lsp-installer')
      installer.on_server_ready(function(server)
        server:setup({})
      end)
    end
  }
  use {'ray-x/lsp_signature.nvim',
    config = function()
      require('lsp_signature').setup({
        hint_enable = false,
      })
    end
  }
end)
```

And here is the result:
![image](https://user-images.githubusercontent.com/446867/150686385-def24e28-9d7a-49e0-9d9e-267415944b10.png)

I noticed that it only happens when `hint_enable` is `false`.

**Comment by ray-x** [comment]
thanks, should be fixed with latest version

**Comment by mbenford** [comment]
It's fixed now. Thanks for such a quick response!
