### ISSUE TITLE
Disable print hover not supported

### ISSUE THREAD

**Issue by seblj** [ray-x/lsp_signature.nvim#16]
I find the printing of hover not supported slightly annoying if I am in a buffer that does not support signature help. It would be great if there was an option for disabling this print

**Comment by tami5** [comment]
Oh god, I came here for the same reason, yah it's pretty annoying. 

@ray-x, I suggest using plenery.log, and if the user want to see error message and debug, he can just let a global variable be true. e.g. `lua _LSPSIG_DEBUG = true`

**Comment by ray-x** [comment]
Thanks for the suggestion.
May I know what lsp you are using? If hover not enabled, does it have any side effects?

**Comment by seblj** [comment]
I have configured python, rust, sqlls, html, vim, vue, json, cpp, css, csharp, bash, lua, typescript and latex, but none of them are active and attached when it's printing.

**Comment by tami5** [comment]
I had the issue with swift language server, I believe this was the first time I had the issue.

**Comment by ray-x** [comment]
Thanks for your advice. I have update plugin and using log now. Unless it is enable, you should not see the print statement
