### ISSUE TITLE
How do I switch to status line?

### ISSUE THREAD

**Issue by eric642** [ray-x/lsp_signature.nvim#160]
pls help me. I used the following configuration. But it didn't work.
```
  local lspsig = require("lsp_signature")
  lspsig.status_line(100)
  lspsig.setup({
    bind = false, -- This is mandatory, otherwise border config won't get registered.
    handler_opts = {
      border = "single"
    }
  })
```

**Comment by eric642** [comment]
Can you give me a detailed example?

**Comment by ray-x** [comment]
Please check my status line config 

https://github.com/ray-x/nvim/blob/98611eb58b5d9a38970ce93cd9f11179c5bef2f8/lua/modules/ui/eviline.lua#L119-L125

**Comment by eric642** [comment]
Thank you. With an example, I know how to do it

**Comment by ray-x** [comment]
Glad to help.
