### ISSUE TITLE
Missing use_lspsaga in README

### ISSUE THREAD

**Issue by jhossbach** [ray-x/lsp_signature.nvim#161]
Hi, I just want to mention that at least one config option is not shown in the README file, namely 'use_lspsaga' (i don't know about the others).
Took me a little to figure this out, maybe you could add it to the list of options there?

**Comment by ray-x** [comment]
It was removed from readme as lspsaga is deprecated.

**Comment by jhossbach** [comment]
There is a [maintained fork](https://github.com/tami5/lspsaga.nvim) of lspsaga which I am using. Also you did not remove the `use_lspsaga` option from the `doc/lsp_signature.txt`. If you consider leaving it in there you should also leave it in the README IMO.

**Comment by ray-x** [comment]
In fact, if you enable use_lspsaga, you will be promoted with a warning message.
I remove the option in doc as you suggested
