### ISSUE TITLE
Error: end_col value is outside range

### ISSUE THREAD

**Issue by stevearc** [ray-x/lsp_signature.nvim#162]
I'm seeing this error during normal usage:

```
Error executing vim.schedule lua callback: ...im/start/lsp_signature.nvim/lua/lsp_signature/helper.lua:565: end_col value outside range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...im/start/lsp_signature.nvim/lua/lsp_signature/helper.lua:565: in function 'highlight_parameter'
        ...nvim/start/lsp_signature.nvim/lua/lsp_signature/init.lua:439: in function 'handler'
        ....mount_nvim3uW8HM/usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

The error occurs when using the typescript language server, and can be triggered
with the following code:
```javascript
const arr = [];
arr.push(
```
As soon as you type the `(`, the error appears

## System information
**OS:** Ubuntu 20.04
**Neovim:** v0.6.1
**lsp_signature.nvim:** latest
**typescript-language-server:** 0.5.4

**Comment by stevearc** [comment]
Update: this happens when the filetype is `javascript.jsx`, but *not* when the filetype is `javascriptreact`.

**Comment by ray-x** [comment]
what is you lsp? tsserver?

**Comment by stevearc** [comment]
Yep! Tsserver 0.5.4

**Comment by ray-x** [comment]
Is the issue fixed?

**Comment by vinioliveira** [comment]
I ran into the same issue, but in my case, the issue was caused by the padding char, I had padding set as ` | `. 
For some reason, this char is breaking the end_col calculation.
