### ISSUE TITLE
`lsp_signature.nvim` overwrites my theme's `FloatBorder` highlight

### ISSUE THREAD

**Issue by xulongwu4** [ray-x/lsp_signature.nvim#163]
I use `nord` as my colorscheme and the `FloatBorder` highlight groups is link to `VertSplit`. However, after the installation of `lsp_signature.nvim`, the highlight of `FloatBorder` is changed to the following:

```
:hi FloatBorder
FloatBorder    xxx guifg=#777777
```

**Comment by xulongwu4** [comment]
It turns out `FloatBorder` is not defined in `nord`. I guess it comes from `nvim`. Closing the issue.

**Comment by xulongwu4** [comment]
I think it is probably not a good idea to define a default highlight group for `FloatBorder` in `lsp_signature`. `nvim` has a default value for it: it links to `VertSplit`. I also have not seen other plugins overwrite the `FloatBorder` highlight. I guess all `lsp_signature` wants is a sane default for `FloatBorder` and `nvim` already provides it for us.

**Comment by ray-x** [comment]
Thanks, Removed.
