### ISSUE TITLE
unfinished capture error

### ISSUE THREAD

**Issue by drusmanbashir** [ray-x/lsp_signature.nvim#167]
Hi, This new error has been appearing for some days when I start calling a particular class method inside python. Ony happens when the class has more than one tuple as a default argument. 

To reproduce, copy-paste below code and start creating an object of this class.
```
class T():
    def __init__(self, chs=(1, 64, 128, 256), num_class=1,o=(1,2)):
        super().__init__()
        pass
```
like so..
```
testing = T(chs=(
```

![Screenshot 2022-02-19 15:27:08](https://user-images.githubusercontent.com/5282314/154807349-2f9b8ced-71c3-49c7-8bac-4740f80dd423.png)

**Comment by ray-x** [comment]
Failed to reproduce.
What is you lsp, pyright, jedi, pylsp?

**Comment by drusmanbashir** [comment]
Hi the lsp is pyright.

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/154866578-bd76008e-ba85-4049-8b43-08adf4e17bcd.png)

It looks good to me.
Could you enable debug mode and capture logs for me?
```lua
 cfg = {
  debug = true, -- set to true to enable debug logging
  log_path = vim.fn.stdpath("cache") .. "/lsp_signature.log", -- log dir when debug is on
 }
require("lsp_signature").setup(cfg)

```
The log should be `~/.cache/nvim/lsp_signature.log`

**Comment by drusmanbashir** [comment]
The error seems to be gone for me too! Thanks for looking into this.
