### ISSUE TITLE
Black background color for special chars in signature

### ISSUE THREAD

**Issue by steliyan** [ray-x/lsp_signature.nvim#169]
This is a JS file and very weird colors are shown. The screenshot is done with the [aurora](https://github.com/ray-x/aurora) theme.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1850292/155894982-2bfe7207-6618-4d39-8bb3-f8b36d1339ce.png">

It's kinda hard to isolate this plugin, given the LSP setup needed, but any directions are welcomed.

Config:
```
require('lsp_signature').on_attach({
    debug = true,
    bind = true,
    hint_enable = false,
    handler_opts = { border = 'rounded' },
    toggle_key = '<M-x>',
  }, bufnr)
```

Edit: Setting the `shadow_blend` and/or `shadow_guibg` doesn't seem to have any effect, although they are properly updated when checking using `:hi FloatShadow` or `:hi FloatShadowThrough`.

<details><summary>Debug log</summary>
`שׁ  |1: insert enter
שׁ  |1: changed
שׁ  |1: {
  triggerCharacters = { "(", ",", "<" }
}
 |2: [].filter(
שׁ  |1: ( |2: true
שׁ  |1: (
שׁ  |1: , |2: false
שׁ  |1: not special |2: ,
שׁ  |1: < |2: false
שׁ  |1: not special |2: <
שׁ  |1: [%(,<][^%(,<%)]*$ |2: %(,< |3: ^%(,<%)
שׁ  |1: last trigger char |2: (
שׁ  |1: lsp cap:  |2: true |3: true |4: 10
שׁ  |1: signature handler
שׁ  |1: sig result |2: {
  bufnr = 1,
  client_id = 2,
  method = "textDocument/signatureHelp",
  params = {
    position = {
      character = 10,
      line = 248
    },
    textDocument = {
      uri = "<SOMETHING>"
    }
  }
}
 |3: {
  activeParameter = 0,
  activeSignature = 0,
  signatures = { {
      documentation = {
        kind = "markdown",
        value = "Returns the elements of an array that meet the condition specified in a callback function."
      },
      label = "filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[]",
      parameters = { {
          documentation = {
            kind = "markdown",
            value = "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array."
          },
          label = "predicate: (value: any, index: number, array: any[]) => value is any"
        }, {
          documentation = {
            kind = "markdown",
            value = "An object to which the this keyword can refer in the predicate function. If thisArg is omitted, undefined is used as the this value."
          },
          label = "thisArg?: any"
        } }
    }, {
      documentation = {
        kind = "markdown",
        value = "Returns the elements of an array that meet the condition specified in a callback function."
      },
      label = "filter(predicate: (value: any, index: number, array: any[]) => unknown, thisArg?: any): any[]",
      parameters = { {
          documentation = {
            kind = "markdown",
            value = "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array."
          },
          label = "predicate: (value: any, index: number, array: any[]) => unknown"
        }, {
          documentation = {
            kind = "markdown",
            value = "An object to which the this keyword can refer in the predicate function. If thisArg is omitted, undefined is used as the this value."
          },
          label = "thisArg?: any"
        } }
    } }
}
 |4: {
  border = "rounded",
  check_pumvisible = true,
  line_to_cursor = "[].filter(",
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<" }
}

שׁ  |1: sig |2: {
  documentation = {
    kind = "markdown",
    value = "Returns the elements of an array that meet the condition specified in a callback function."
  },
  label = "filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[]",
  parameters = { {
      documentation = {
        kind = "markdown",
        value = "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array."
      },
      label = "predicate: (value: any, index: number, array: any[]) => value is any"
    }, {
      documentation = {
        kind = "markdown",
        value = "An object to which the this keyword can refer in the predicate function. If thisArg is omitted, undefined is used as the this value."
      },
      label = "thisArg?: any"
    } }
}
 |3: 0
שׁ  |1: func |2: filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[] |3: {
  documentation = {
    kind = "markdown",
    value = "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array."
  },
  label = "predicate: (value: any, index: number, array: any[]) => value is any"
}

שׁ  |1: cleanup vt |2: 19
שׁ  |1: md lines trim |2: { "```j", "filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[]", "```", "Returns the elements of an array that meet the condition specified in a callback function.", "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array." }

שׁ  |1: line1 is markdown reset offset to 3
שׁ  |1: before insert |2: { "```j", "filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[]", "```", "Returns the elements of an array that meet the condition specified in a callback function.", "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array." }

שׁ  |1: label: |2: filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[] |3: 0 |4: 1 |5: 0 |6: {
  documentation = {
    kind = "markdown",
    value = "Returns the elements of an array that meet the condition specified in a callback function."
  },
  label = "filter(predicate: (value: any, index: number, array: any[]) => value is any, thisArg?: any): any[]",
  parameters = { {
      documentation = {
        kind = "markdown",
        value = "A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array."
      },
      label = "predicate: (value: any, index: number, array: any[]) => value is any"
    }, {
      documentation = {
        kind = "markdown",
        value = "An object to which the this keyword can refer in the predicate function. If thisArg is omitted, undefined is used as the this value."
      },
      label = "thisArg?: any"
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_pumvisible = true,
  close_events = { "BufHidden" },
  focus_id = "lsp_signature699",
  line_to_cursor = "[].filter(",
  max_height = 12,
  max_width = 80,
  offset_x = -6,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<" },
  zindex = 200
}

שׁ  |1: {
  anchor = "NW",
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  col = -6,
  height = 10,
  relative = "cursor",
  row = 1,
  style = "minimal",
  width = 80,
  zindex = 200
}
 |2: 0 |3: 9
שׁ  |1: floating opt |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_pumvisible = true,
  close_events = { "BufHidden" },
  focus_id = "lsp_signature699",
  focusable = true,
  line_to_cursor = "[].filter(",
  max_height = 10,
  max_width = 80,
  offset_x = -6,
  offset_y = 0,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<" },
  zindex = 200
}
 |3: {
  anchor = "NW",
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  col = -6,
  height = 10,
  relative = "cursor",
  row = 1,
  style = "minimal",
  width = 80,
  zindex = 200
}

שׁ  |1: sig_cfg new bufnr, winnr  |2: 6 |3: 1007
שׁ  |1: extmark |2: 6 |3: 8 |4: 75 |5: 0 |6: LspSignatureActiveParameter
שׁ  |1: extmark |2: 6 |3: 7 |4: 75 |5: 0
שׁ  |1: extmark_id |2: 1`

</details>

**Comment by ray-x** [comment]
I could not reproduce this one
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1681295/158701689-1956c191-6509-4f9d-89ef-e01c041cf806.png">
Might be setup elsewhere, e.g. token/special_key background
