### ISSUE TITLE
Use backtick decorator doesn't highlight parameter

### ISSUE THREAD

**Issue by vpeopleonatank** [ray-x/lsp_signature.nvim#17]
Here is my lsp-signature config
```
cfg = {
  bind = true, -- This is mandatory, otherwise border config won't get registered.
              -- If you want to hook lspsaga or other signature handler, pls set to false
  doc_lines = 10, -- only show one line of comment set to 0 if you do not want API comments be shown

  hint_enable = true, -- virtual hint enable
  hint_prefix = "🐼 ",  -- Panda for parameter
  hint_scheme = "String",

  handler_opts = {
    border = "single"   -- double, single, shadow, none
  },
  decorator = {"`", "`"}  -- or decorator = {"***", "***"}  decorator = {"**", "**"} see markdown help
}

```
I 've changed decorator to * and **, It output italic and bold parameter. But when change to backtick, parameter isn't highlighted 
![image](https://user-images.githubusercontent.com/30976876/118415271-a0610680-b6d3-11eb-828f-0fa17bdab4b2.png)

**Comment by ray-x** [comment]
Thanks for the PR.
This is link to this : https://github.com/nvim-treesitter/nvim-treesitter/issues/1273#issuecomment-830978552
It may not stick to treesitter.  The key point is that the markdown does not render the filetype together with the signature.
So instead of getting

```python
def ab():
    pass
```

You got 
```
def ab():
    pass
```

I am waiting on the upstream changes been merged.

**Comment by vpeopleonatank** [comment]
I 'll close this issue, when upstream changes been merged. :)

**Comment by Shatur95** [comment]
@vpeopleonatank, how did you get a border for floating window?

**Comment by vpeopleonatank** [comment]
@Shatur95 As far as I remember, It comes from lspsaga https://github.com/glepnir/lspsaga.nvim

**Comment by ray-x** [comment]
this should do.
```lua
    require "lsp_signature".on_attach({
      bind = true, -- This is mandatory, otherwise border config won't get registered.
      handler_opts = {
        border = "single"
      }
    })
```

**Comment by Shatur95** [comment]
@ray-x, thank you!

**Comment by ray-x** [comment]
This issue should been fixed in the latest version. 
Please check the latest version. Thanks!
