### ISSUE TITLE
feat: set a global variable on opening / closing the signature help floating window

### ISSUE THREAD

**Issue by Bekaboo** [ray-x/lsp_signature.nvim#170]
![image](https://user-images.githubusercontent.com/76579810/159179755-eda755de-eb93-4ed6-beaa-4b4d26c2bc15.png)
This can be used to avoid overlapping with cmp completion floating windows by disable cmp temporarily when the global variable (say, `lsp_signature_help`) is true.

**Comment by ray-x** [comment]
you can use this configure:
```
  toggle_key = nil -- toggle signature on and off in insert mode,  e.g. toggle_key = '<M-x>'

```

**Comment by ray-x** [comment]
@Bekaboo 
Is toggle_key works for you?
