### ISSUE TITLE
active parameter not highlighted

### ISSUE THREAD

**Issue by redxtech** [ray-x/lsp_signature.nvim#174]
Hey, I'm using this plugin with the dracula colourscheme, and I've notice that the parameter specified by `LspSignatureActiveParameter` isn't getting highlighted. I've tested it with another colourscheme (catppuccin) and it was working with that one.

Is this something I'm going to open an issue with on the dracula repo? Is it not specifying a certain colour?

**Comment by ray-x** [comment]
Do you have a code snippet (your function signature). I can reproduce this?
It may be related to the LSP/language you working on.

**Comment by redxtech** [comment]
It's the same for every function, in every language, but here are some screenshots:
TS (deno) dracula theme: https://i.imgur.com/8eiRYmN.png
TS (deno) catppuccin theme: https://i.imgur.com/Xw8SyFD.png
JS (tsserver) dracula theme: https://i.imgur.com/cGiKerC.png
JS (tsserver) catppuccin theme: https://i.imgur.com/L6XIHcK.png

**Comment by ray-x** [comment]
Could you check if it works with other colorschemes, e.g. `default`
below is what I saw for js when using `default`

<img width="394" alt="image" src="https://user-images.githubusercontent.com/1681295/162641808-df5cea29-5ce4-4142-adb1-1092f03ce0fe.png">

**Comment by redxtech** [comment]
This is what it looks like without a theme for me:
https://i.imgur.com/ilByD0C.png

**Comment by ray-x** [comment]
Ok, I think it may be related to your environment.
Could you check 
1) checkhealth and post any warnings/errors
2) your minimum vimrc that I can reproduce the issue.
3) Your OS and output of `nvim --version`

**Comment by redxtech** [comment]
Alright, here's my OS, versiom, & the most minimal `init.lua` that I was able to reproduce.

**OS:** arch linux
**NVIM Version:**
I usually use the latest version available, here's that output
```
NVIM v0.7.0-dev+1425-gff726cc56
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-690

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Here's the same output for my system neovim:
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Checkhealth:**
The only warnings were `neovim-ruby-host` not found, and "Neovim::Ext" cpan module not installed,

**init.lua:**
```lua
-- init.lua
require('plugins')
require('opts')
require('lsp')
require('binds')

-- plugins.lua
return require('packer').startup(function()
	use 'wbthomason/packer.nvim'
	use {'dracula/vim', as = 'dracula'}
	use {'catppuccin/nvim', as = 'catppuccin'}
	use 'neovim/nvim-lspconfig'
	use 'ray-x/lsp_signature.nvim'	
end)

-- opts.lua
vim.cmd('colo dracula')
vim.cmd('syntax on')

-- lsp.lua
local on_attach = function(client, bufnr)
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
  require('lsp_signature').on_attach()
end
local nvim_lsp = require('lspconfig')
nvim_lsp.denols.setup {
  on_attach = on_attach,
  root_dir = nvim_lsp.util.root_pattern('deno.json'),
  init_options = {
    lint = true,
  },
}
nvim_lsp.tsserver.setup {
  on_attach = on_attach,
  root_dir = nvim_lsp.util.root_pattern('package.json'),
  init_options = {
    lint = true,
  },
}


-- binds.lua
-- only mappings in here but i can include it if necessary
```

**Comment by ray-x** [comment]
I think may relate to your tsserver version.

I have push 
https://github.com/ray-x/lsp_signature.nvim/blob/master/tests/init_pack.lua

and it works fine for tsserver

<img width="268" alt="image" src="https://user-images.githubusercontent.com/1681295/162731879-e0948b3e-c7eb-4405-af27-788753ba2372.png">

**Comment by redxtech** [comment]
Getting the same with pyright: https://i.imgur.com/QOD1V3C.png

**Comment by redxtech** [comment]
I have just figured out that it works when I add this to my `plugins.lua`:
```lua
use {
	'ray-x/lsp_signature.nvim',
	config = function()
		require("lsp_signature").setup({}) -- i was previously not using this setup call
	end
}
```
Previously, I only had the `require "lsp_signature".on_attach()` in the lsp `on_attach` function, shown [here in my config](https://github.com/redxtech/dotfiles/blob/043326bd95a858e57b9eb209adb3526abf57ac60/.config/nvim/lua/lsp.lua#L112).

However, it appears as though this isn't needed, so I will be dropping it and only using the setup call in my plugins file.
