### ISSUE TITLE
Disable signature help if the language server does not support it

### ISSUE THREAD

**Issue by akinsho** [ray-x/lsp_signature.nvim#178]
Hi, 

I can't seem to find out how I can disable this plugin in languages where the LSP doesn't support signature help. For example, I am using `terrformls` and it doesn't support signature help, which is fine, but this plugin echoes an error on insert mode whilst it is trying to find the signature but the LSP doesn't return it. Is there some way to manually disable a client or better still can this plugin use `resolved_capabilities` (eventually `server_capabilities`) to check if it is supported by the client before trying to show it.

**Comment by ray-x** [comment]
If you are using nvim > 0.6.1 
The plugin will check `value.server_capabilities.signatureHelpProvider` and if it is nil, will not send signature requests to the server.

**Comment by akinsho** [comment]
@ray-x `server_capabilities` is only available in the latest nightly, it won't work for people on stable 0.7.

**Comment by ray-x** [comment]
In fact, it not true, there is a long time resolved_capabilities and server_capabilities co-existed.
Also if server_capabilities not existed it will fallback to resolved_capablilities.

**Comment by akinsho** [comment]
@ray-x thanks for clarifying, I just verified this is in fact the case. One thing that I'm noticing though is that `server_capabilities` sometimes returns `<capability>Provider = vim.empty_dict()` in this case should this be counted as something that is supported or not? Since there are some which are `true` and others which are `{key = value}`

**Comment by ray-x** [comment]
That is a not support. As it does not provides the triggerCharacters list. So it should not be triggered. Unlessa `extra_trigger_chars` is defined.

**Comment by akinsho** [comment]
@ray-x FWIW whilst using terraform ls I still get this error when entering any terraform buffer, not sure what's going on with server capabilities it shows its capability as `signatureHelpProvider = vim.empty_dict()` but this plugin is still triggered, and I see
`RPC[Error] code_name = MethodNotFound, message = "method not found" data = "textDocument/signatureHelp"` error constantly when switching buffers.

I think the check that should disable this plugin for this lsp does not work, probably. I can't see the `extra_trigger_chars` field anywhere

**Comment by akinsho** [comment]
For reference there is an issue in nvim core about this https://github.com/neovim/neovim/issues/18939 whatever the solution is there won't help me though since this plugin is what controls calling signature help so a fix is needed here as well

**Comment by akinsho** [comment]
@ray-x not sure how you want to handle it since upstream thinks it's a bug with terraform ls, but I'm wondering if it's worth adding a filetype block list at least so I can disable this plugin for terraform files. It also has the advantage of maybe being useful for other users who might not want signature help in some filetypes for some reason (although this is a somewhat unconvincing use case 😅 )
