### ISSUE TITLE
Error `attempt to index a userdat`

### ISSUE THREAD

**Issue by sharksforarms** [ray-x/lsp_signature.nvim#179]
Got the following which editing a perl file using `perlpls`

Any ideas how to debug this?

```
Error executing vim.schedule lua callback: ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:509: attempt to index a userdat
a value
stack traceback:
        ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:509: in function 'signature'
        ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:581: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by ray-x** [comment]
I have zero experience with perl. Could you enable the log by setting `debug=true` and send me the log
by  default log is here `vim.fn.stdpath("cache") .. "/lsp_signature.log"`

**Comment by sharksforarms** [comment]
Hm, having a hard time reproducing this... I'll let you know once I have a repro.
