### ISSUE TITLE
How do you switch the docs for overloads?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ray-x/lsp_signature.nvim#183]
For example, I see this: 

![image](https://user-images.githubusercontent.com/199018/169076263-4a9d5ce9-5cf6-4bfe-aea8-e94b3d27d28e.png)

I'd like to see the docs for each of the overload options.

- Is it possible to setup a key-binding for this?
- Is it possible to setup a key-binding for scrolling? (I have one for nvim-cmp)

**Comment by Issafalcon** [comment]
I'd also like to see this feature to have keybinds to switch between the overload docs (and scroll up and down on the docs)

Using this plugin with the omnisharp-lsp brings up all the overloads correctly, and it's true that typing in the arguments refreshes the UI. However, this only works if the overload you are using has the same initial argument types as the first (top) signature. If the argument types are different, and you start typing an argument of a different type, all lsp-signature functionality seems to stop working.

Take the `string.Compare()` function in C# for example:

![image](https://user-images.githubusercontent.com/19861614/173228420-bb9c8648-60b9-4b3e-b1dc-34df1c447e20.png)

No problems if you want to use an overload with the same initial arguments as the top one:
![image](https://user-images.githubusercontent.com/19861614/173228493-516ea3aa-2a88-4d71-89e0-a7c5dc354b51.png)

But using an overload from the bottom of the list just seems to break the functionality:
![image](https://user-images.githubusercontent.com/19861614/173228529-32a18c61-8a50-44d0-8e5a-ddffd5910302.png)

When trying to use an overload with different parameter types from the bottom, I get these error responses:
![image](https://user-images.githubusercontent.com/19861614/173228691-ebddd95c-b672-4860-ae57-11a2843f7a96.png)

**Comment by Issafalcon** [comment]
I'm not sure if the above is specific to the omnisharp-lsp, or can also be seen with other lsp servers with overloaded methods.

**Comment by ray-x** [comment]
@NullVoxPopuli 
I noticed I added support for switch between signature with keybinding but I did not update the document. Could you check if the select_signature_key setup works for you. Thanks!
