### ISSUE TITLE
signature help introduce delays on holding Backspace

### ISSUE THREAD

**Issue by mortezadadgar** [ray-x/lsp_signature.nvim#184]
Hey,
I notices serious delays(or stutters) when I tries to removes a functions on a line that has more than two signature help
like
```
const num = 1
const hello = "Hello"
const name = "World"
fmt.Fprintf(os.Stdout, "%d: %s %s\n", num, hello, name) | <- hold Backspace from here and see the text slowly getting removed
```

https://user-images.githubusercontent.com/27911493/170338388-688c2dd6-2d22-410c-9a71-52e18b995727.mp4

**Comment by mortezadadgar** [comment]
Any thought?

**Comment by ray-x** [comment]
Not so sure what the issue is.  Do you mean the cmp Pmenu overlap with signature floating windows from 0:02?

**Comment by mortezadadgar** [comment]
> Not so sure what the issue is. Do you mean the cmp Pmenu overlap with signature floating windows from 0:02?

No, there are delays caused by signature help if you disable this plugin it's very noticeable

**Comment by ray-x** [comment]
https://user-images.githubusercontent.com/1681295/178429033-7ebef21c-1fd4-4acf-a434-e54fafc5f509.mp4

I do not see much issue here. Did you enabled debug log or is there are other thing in you config slow down backspace?

**Comment by mortezadadgar** [comment]
I expect completion floating window to not lags while removing function argument, would you test this with nvim-cmp enabled and again with lsp signature disabled so you will notice delays I suppose

**Comment by ray-x** [comment]
https://user-images.githubusercontent.com/1681295/178476330-1bffb390-eea3-4a07-9469-b603ad0dc7e8.mp4
As in the first and this video, I remove the comment line on purpose for comparison. I can not see much difference if I remove the comment line and the line with a valid signature. 
Adding cmp and re-run the test, Do not see much difference

Regarding the lags, that highly depends on 
1) refresh timer. As I mentioned, the refresh rate is 200ms, you can increase the rate by setting it to 30, but I do not see much benefit
2) the speed of you lsp. Some of them are slow, e.g. tsserver, pyright, pylsp. There also reports from users of rust-analyser said it is too slow.
3) Any other plugin that listens on CursorMoveI, TextChangedI  event

**Comment by mortezadadgar** [comment]
ok I understand
