### ISSUE TITLE
Adjust floating window under current line

### ISSUE THREAD

**Issue by jiashun0011** [ray-x/lsp_signature.nvim#186]
Hi,

I want know whether there is any approach to put the floating window under current line.

Looks like the default config is above the current line.

```
  ...
  floating_window = true, -- show hint in a floating window, set to false for virtual text only mode

  floating_window_above_cur_line = true, -- try to place the floating above the current line when possible Note:
  -- will set to true when fully tested, set to false will use whichever side has more space
  -- this setting will be helpful if you do not want the PUM and floating win overlap

  floating_window_off_x = 1, -- adjust float windows x position.
  floating_window_off_y = 1, -- adjust float windows y position.
  ...                                            
```

Thanks

**Comment by ray-x** [comment]
Because the autocomplete will popup below the current line in most cases, it would be good to put the floating windows above the current line.
`floating_window_above_cur_line` will further ensure it is above the current line unless the space is not large enough.
Why you would want it below the current line?

**Comment by jiashun0011** [comment]
> Because the autocomplete will popup below the current line in most cases, it would be good to put the floating windows above the current line. `floating_window_above_cur_line` will further ensure it is above the current line unless the space is not large enough. Why you would want it below the current line?

Ah, it makes sense and thanks for replying.

**Comment by gerazov** [comment]
Great plugin! :sunglasses: 

It would be useful to have a `floating_window_below_cur_line` in opposition to `floating_window_above_cur_line`. 

Usually when you write a function you're variables are defined above the current line and it's useful to have them in plain sight when using them as arguments.

Here's a screenshot where the pop-up hides the code necessary to write the command even though there's plenty of space below the current line (23 lines of code till end of view). 

![image](https://user-images.githubusercontent.com/15214418/200607278-f082c97d-e34d-4597-9539-756f9e6505ed.png)

**Comment by dixler** [comment]
I also have this issue as I've been centering the cursor on the screen via
`let &scrolloff=999-&scrolloff`
