### ISSUE TITLE
parameter highlighting and window help

### ISSUE THREAD

**Issue by euler007** [ray-x/lsp_signature.nvim#187]
Hi, 
I am new to lua type configuration and have shifted to neovim from vim recently. I found this plugin and managed to get it work but there are a couple of issues I am facing:

1. The lsp window clashes with this floating window, both open at the same time and overlap each other. I would much rather prefer lsp-signature window to stay open
2. I cant seem to get highlighting of parameters working

In the lsp.handlers file I have plugged in require'lsp_signature'.on_attach() right after M.on_attach method on line 89

I am using the same config as [this](https://github.com/LunarVim/Neovim-from-scratch/tree/06-LSP) . I understand that developing my own config would help in a better understanding but I did not have the bandwidth of starting from scratch and wanted to keep my vim and neovim configs separate for hygiene purposes, so taking this as a base also because of the presence of some very nice video tutorials.

**Comment by ray-x** [comment]
I could you send
1) screenshot or recording when issue is happen
2) how to reproduce. The lsp you are using, and the code signature when the plugin failed.
Thanks!

**Comment by euler007** [comment]
Figured it out, no worries. Thanks!
