### ISSUE TITLE
'height' key must be a positive Integer

### ISSUE THREAD

**Issue by vsedov** [ray-x/lsp_signature.nvim#189]
```lua
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1537: 'height' key must be a p
ositive Integer                                                                                                       
stack traceback:                                                                                                      
        [C]: in function 'nvim_open_win'                                                                              
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1537: in function 'open_floating_preview'                        
        ...packer/opt/lsp_signature.nvim/lua/lsp_signature/init.lua:458: in function 'handler'                        
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1173: in function ''                                                  
        vim/_editor.lua: in function <vim/_editor.lua:0>```
```

Got this erorr when trying to complete something on second line of any file  with lsp  

quick replication of error if you wish : 

open python file nvim test.py 

write print() - should work normally on line one 
write print() - again and it should proceed to give an error shown above.

**Comment by bryant-the-coder** [comment]
i am having the same issue too

**Comment by ray-x** [comment]
Failed to reproduce
<img width="653" alt="image" src="https://user-images.githubusercontent.com/1681295/173453800-2508737f-2b22-4ff9-a15c-424f9842e211.png">

**Comment by ray-x** [comment]
I push a check for this, not sure if it will works for you

**Comment by vsedov** [comment]
> I push a check for this, not sure if it will works for you

Cheers, il check it out now :)

**Comment by vsedov** [comment]
Update : Seems like it has fixed the issue, thanks for the quick fix :)
