### ISSUE TITLE
The parameter is not highlighted when we use FixCursorHold.nvim together

### ISSUE THREAD

**Issue by rockyzhang24** [ray-x/lsp_signature.nvim#192]
Recently I added a new plugin [FixCursorHold.nvim](https://github.com/antoinemadec/FixCursorHold.nvim) and I found the parameter highlight feature stopped working. 

Thank you.

**Comment by WieeRd** [comment]
Can confirm, this happens to me as well.  
Parameter highlight works again after removing `FixCursorHold.nvim`

**Comment by ray-x** [comment]
From the explanation of FixCursorHold
1) signature using a timer of 200ms by default
2) signature is CursorHold to update statusline
As it is not an essential feature you can disable by setting `cursorhold_update` to false.

**Comment by WieeRd** [comment]
After updating, the problem did get fixed by adding `cursorhold_update = false`. Thanks!
```lua
require("lsp_signature").setup({ cursorhold_update = false })
```
