### ISSUE TITLE
Black background on popup

### ISSUE THREAD

**Issue by otavioschwanck** [ray-x/lsp_signature.nvim#193]
The popup not respect other popups, like cmp.

signature:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/9551316/176061690-2b346ad8-21a1-41a2-9ce5-fce61921ea1f.png">

other popups:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/9551316/176061728-bbaf7a89-8283-42cc-b4da-d139d931c57c.png">

OS: Mac.

Config: https://github.com/otavioschwanck/mood-nvim/blob/main/lua/user_lsp.example.lua

**Comment by ray-x** [comment]
You can tune z-index so CMP can have higher priority.
There are limitations. When signature popup, it has no idea if cmp/Pmenu will popup or not. If cmp/Pmenu is already shown it will not cover those popups.

**Comment by ray-x** [comment]
Could you check the latest version with wrap option ?

**Comment by otavioschwanck** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/9551316/178640407-7b2678c2-b084-415a-8d78-42405304c2e9.png">

Still with black box, wrap active.

 ✓ ray-x/lsp_signature.nvim: already up to date

**Comment by ray-x** [comment]
If you talking about the border background color.  You need to find a colorscheme defined `FloatBorder ` and `Float` which  matchs your background (Normal).
