### ISSUE TITLE
Active in Normal Mode

### ISSUE THREAD

**Issue by ChristianChiarulli** [ray-x/lsp_signature.nvim#198]
![image](https://user-images.githubusercontent.com/29136904/178399229-860bce35-abd1-431f-9673-6ebb033ffda5.png)

**Comment by ChristianChiarulli** [comment]
Before recently this plugin was only active in insert mode is there any way to bring back that behavior or is this a bug?

**Comment by ray-x** [comment]
Yes, it is a bug, fixed
