### ISSUE TITLE
Option to extend `triggered_chars`

### ISSUE THREAD

**Issue by weeman1337** [ray-x/lsp_signature.nvim#2]
Why? I want to improve the experience while typing.

For example my LS returned the chars `(` and `,`.

Now if I am typing `in_array('test', _)` (where `_` is the cursor) there is no completion. Now I am just before starting the next parameter but there is no completion anymore. For me I want to add ` ` (space) to the trigger list event at this point.

**Comment by ray-x** [comment]
Should have been fixed in version: 1a248103438

**Comment by weeman1337** [comment]
Works. Thanks!
