### ISSUE TITLE
lsp function signature on cursor in normal mode

### ISSUE THREAD

**Issue by kskarthik** [ray-x/lsp_signature.nvim#200]
Hi, I saw the project's demo clip, when cursor is placed on a function in normal mode, shows the function's docstring, But i am unable to see that behaviour in my setup. Is there any option to enable that behaviour? Is #198 related to this?

**Comment by ambadyanands** [comment]
Currently signature hint works only in insert mode (from what I tested). It'd be good if there's an option to toggle this feature in normal mode for those who want it.

**Comment by ray-x** [comment]
you can setup normal keymap to trigger lsp.buf.signature_help() in normal node, that will show the lsp_signature

**Comment by ray-x** [comment]
It works in both insert mode and normal mode. Normal mode will require a trigger key to trigger the signature help as mentioned above.

**Comment by kskarthik** [comment]
@ray-x thanks for your help!
