### ISSUE TITLE
Plugin errors a lot since some time (bad argument #1 to `getinfo`)

### ISSUE THREAD

**Issue by B4mbus** [ray-x/lsp_signature.nvim#201]
Hey. Since some time (about a week) the plugin errors a lot.

I'm using the latest version, `neovim` version 0.7.0 and LunarVim version `e1d32ca`.

Here are two relevant GIFs.

![ooga](https://user-images.githubusercontent.com/75364377/179545506-301c49ba-43c2-4c25-a896-dec6daa7ccf8.gif)

![ooga2](https://user-images.githubusercontent.com/75364377/179545521-e7656201-b322-4fd4-9d27-9cf6dfb79aba.gif)

**Comment by ray-x** [comment]
Should be fixed now.
