### ISSUE TITLE
Wrong highlighting when parameter-name is contained in the function-name

### ISSUE THREAD

**Issue by zacmar** [ray-x/lsp_signature.nvim#21]
Consider
```
import torch as th
a = th.randperm(10)
```

Put the cursor on `10` and look up signature help:
![2021-06-01-114009_600x114_scrot](https://user-images.githubusercontent.com/32982619/120302370-1ff2f600-c2ce-11eb-93b5-69a58201a768.png)
The 'n' in `randperm` is erroneously highlighted instead of the actual parameter.

**Comment by ray-x** [comment]
the lsp should not return n, instead it should return `n: _int`
Are you using pyright?

If you are using pyls strongly recommend you change to pyright, pyls has been out of maintain for more than 6 months.

Meanwhile, although my pyls is broken (some depency breaks...) I am trying to match the whole word, which is `n` in your case in the new version.

**Comment by zacmar** [comment]
Yes, I was using pyls. Thanks for the heads-up, it works with pyright :+1:.
