### ISSUE TITLE
Syntax highlighting for the floating window

### ISSUE THREAD

**Issue by UtkarshVerma** [ray-x/lsp_signature.nvim#215]
Would it be possible to have syntax highlighting for the function definition in the floating window? Maybe something related to treesitter?

**Comment by ray-x** [comment]
highlight is rendered with embedded markdown highlight. It does not support treesitter unless upstream support it. But it should support basic highlights.

**Comment by UtkarshVerma** [comment]
Okay, thanks for the quick info and thanks for making such a nice extension!

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/187313937-86c12aca-88ac-45ee-9c47-ceab9cb7862a.png)

Just in case you(or anyone) do not see any highlight (e.g. `int` and `char` should be highlighted in the above image). Feel free to reopen the ticket and specify the LSP you are using.
