### ISSUE TITLE
error on signature window open

### ISSUE THREAD

**Issue by akinsho** [ray-x/lsp_signature.nvim#22]
Hi 👋🏾 ,

I'm trying this plugin whilst working with dartls and everytime the signature window opens I get a 
```
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:175: attempt to perform arithmetic on local 's' (a nil value)
```

https://github.com/ray-x/lsp_signature.nvim/blob/94eb5ca14b74511efd29ddd56e5b8a22f4ac4496/lua/lsp_signature.lua#L175
This seems to be coming from this line above, likely because the `s` value is returning nil when trying to match a the active parameter. Dart has labelled arguments like `my_param: value` so I don't know if this somehow breaks fetching the active parameter.

**Comment by ray-x** [comment]
@akinsho 
Well...
Did some debug, and I found dartls does not support activeParameter. which means, it always return -1

Here is a sample response:

```lua
{
  activeParameter = -1,
  activeSignature = 0,
  signatures = { {
      label = "add3(int n, int m, int p)",
      parameters = { {
          label = "int n"
        }, {
          label = "int m"
        }, {
          label = "int p"
        } }
    } }
}
```

I am trying to fallback the result and it should works for you

**Comment by akinsho** [comment]
Just tried it out and seems to work, I'm actually seeing the active parameter being highlighted now. If dart ls doesn't support it how is that possible? is the plugin inferring something based on separators like comma or something? either way it's a good result, thanks 🙏🏾

**Comment by akinsho** [comment]
Actually it isn't actually the correct parameter for named arguments but that's fine it doesn't break and if the lsp doesn't support it there's not really much this plugin can do 🤷🏾

**Comment by akinsho** [comment]
Will close this out now since it isn't erroring anymore, maybe will raise something upstream about the lack of support. Do you know if maybe it just needs a capability to be specified on init that's missing or did you specify that already in your test?

**Comment by ray-x** [comment]
My implementation is to count the trigger character provided by LSP.
It would be great to open an issue upstream so dartls can send activeParameter through. so it can look like etc `activeParameter = 1,`
My code check `signature_help` in capability. There is no capability for `activeParameter`

**Comment by akinsho** [comment]
@ray-x I dug through the dartls code and there's a big todo there and it seems to be a known feature that is missing. I'll take it up with them 👍🏾
