### ISSUE TITLE
Toggle signature when in select mode - golang function arguments placeholders

### ISSUE THREAD

**Issue by ziombo** [ray-x/lsp_signature.nvim#222]
I have lsp_signature disabled by default and show it when needed with the use of toggle_key set in config. This works great until I'm in a function which has filled placeholders by gopls (language server). Then it initially start with the first parameter selected and wait for a keypress to replace it and enter insert mode in which I can toggle the documentation, however I sometimes want to toggle the signature, to know what kind of arguments are expected.

Can't toggle signature:
![image](https://user-images.githubusercontent.com/15613606/192051267-c72d2aea-c5ca-49be-921e-3f5f99991b63.png)

after pressing 'l' I can toggle the signature with my toggle_key:
![image](https://user-images.githubusercontent.com/15613606/192051415-8c72a623-ffbe-4914-8083-a359e40b4d8b.png)

**Comment by ray-x** [comment]
Do you know what is the vim mode when you are in placeholders?
Also what is the snippet plugin you are using?

**Comment by ziombo** [comment]
How could I check the current vim mode without interrupting the mode itself?
I'm using LuaSnip, but like I mentioned the screenshot is coming from Gopls setting [_usePlaceholders_ ](https://go.googlesource.com/tools/+/refs/tags/gopls/v0.2.0-pre1/gopls/doc/settings.md)

**Comment by ray-x** [comment]
In your statusline, it should show the current vim mode.

**Comment by ziombo** [comment]
It's in SELECT mode

**Comment by ray-x** [comment]
I added keymap for both visual and select mode. Hope it helps.

**Comment by ziombo** [comment]
Works like a charm. Thanks!
