### ISSUE TITLE
Signature in status line doesn't seem to work in bare config. What is missing?

### ISSUE THREAD

**Issue by 0x0DEADBEE** [ray-x/lsp_signature.nvim#230]
I was going to replace [echodoc.vim plugin](https://github.com/Shougo/echodoc.vim) using [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim). I followed exactly as documentation says, and yet It doesn't work. [(this is the minimal config (init.lua))](https://github.com/0x0DEADBEE/dotfiles/tree/echoDoc). (check out echoDoc function)
I think it's missing somethings out of the documentation because I have pasted the code inside [LunarVim](https://github.com/lunarvim/lunarvim) config file and it does work..

**Comment by ray-x** [comment]
You can take a look of my statusline setup here:
https://github.com/ray-x/nvim/blob/85b37a62fb26702897be94ca156e099caa3ffa61/lua/modules/ui/eviline.lua#L98-L108

**Comment by 0x0DEADBEE** [comment]
replaced my code with yours. still doesn't work. Other features work

**Comment by 0x0DEADBEE** [comment]
installed bare treesitter as well: no results

**Comment by 0x0DEADBEE** [comment]
tried to `lua print(require("lsp_signature").status_line(100).label)`, still no result

**Comment by ray-x** [comment]
well, maybe we try this: 
1) your lsp is up and running, `LspInfo`
2) you park your cusror inside a function, e.g.       `funcname(arg1, arg2, arg3)`  you park your cursor on `r` of `arg1`
3) lua print(require("lsp_signature").status_line(100).label)

**Comment by 0x0DEADBEE** [comment]
``` Use [q] or [Esc] to quit the window
 
 Language client log: /home/matteo/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 1 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, pid: nil, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio
 
 Configured servers list: clangd, pyright, sumneko_lua
```
`lua print(require("lsp_signature").status_line(100).label)` gave me no result

**Comment by 0x0DEADBEE** [comment]
I tried to run the command even on LunarVim; `:LspInfo` gave me the same result but sumneko_lua and clang weren't in ` Configured servers list` (due to lazy loading or better config maybe)
I'm running on Fedora's spin i3, I kindly ask you to "reproduce" my environment on  Virtual Box for example. As I already said, I followed the doc, therefore something is missing from there. Ty very much!

**Comment by 0x0DEADBEE** [comment]
I made it! I just had to update "updatetime" value to 0.3 sec. Now it works like a charm!
for anyone interested, just checkout my "echoDoc" branch (https://github.com/0x0DEADBEE/dotfiles/tree/echoDoc)

**Comment by ray-x** [comment]
what was your setup of update time? Mine is 1sec.

**Comment by 0x0DEADBEE** [comment]
it was 3 sec. I set 0.3 sec

**Comment by ray-x** [comment]
ok, 3s is a bit too long. That might be why you do not see the updated info.
