### ISSUE TITLE
the hint sometimes shows and sometimes not

### ISSUE THREAD

**Issue by kulakilam** [ray-x/lsp_signature.nvim#236]
https://user-images.githubusercontent.com/4487126/203823724-0e490fb6-9e19-4ab8-a55d-36150fbafee0.mov

it seems that the hint can't show in the higher lines, but shows in the lower lines.
I guess the hint is covered by the signature help

**Comment by ray-x** [comment]
it might be because the hint was blocked by floating windows.

**Comment by kulakilam** [comment]
> it might be because the hint was blocked by floating windows.

this is my minimal init.vim which can reproduce this issue:
```
set expandtab
set shiftwidth=4
set tabstop=4

call plug#begin()
Plug 'neovim/nvim-lspconfig'

Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-vsnip'
Plug 'hrsh7th/vim-vsnip'

Plug 'ray-x/lsp_signature.nvim'
call plug#end()

lua << EOF

require('lspconfig').ccls.setup{}
require('cmp').setup{}
require('lsp_signature').setup()

EOF
```
additional information:
- vim version: 0.8.1
- plugins' versions: all latest version

https://user-images.githubusercontent.com/4487126/203905513-4b72eecd-8943-4a76-9418-de92971c2dfd.mov
