### ISSUE TITLE
out of range with C functions that uses elipsis e.g.: printf, fprintf, and etc...

### ISSUE THREAD

**Issue by lbiaggi** [ray-x/lsp_signature.nvim#24]
Hi, when using this plugin with functions that can accept literally any variable number of parameters in C gave this error.

![image](https://user-images.githubusercontent.com/5401584/120491691-d4a11c00-c38f-11eb-9df6-28bf0e61e096.png)

It didn't bother me that much, I'm just reporting because I think it can impact in other languages.

**Comment by ray-x** [comment]
<img width="681" alt="Screen Shot 2021-06-03 at 12 10 38 am" src="https://user-images.githubusercontent.com/1681295/120495560-297c7b00-c400-11eb-8e5c-72ba90bef2f7.png">
Can not reproduce. What language server you are using? Clangd?

**Comment by pianocomposer321** [comment]
I get this with lua as well:
![error](https://user-images.githubusercontent.com/54072354/120496039-d9130800-c382-11eb-8be4-bcfee736e4c7.png)

**Comment by lbiaggi** [comment]
> <img alt="Screen Shot 2021-06-03 at 12 10 38 am" width="681" src="https://user-images.githubusercontent.com/1681295/120495560-297c7b00-c400-11eb-8e5c-72ba90bef2f7.png">
> Can not reproduce. What language server you are using? Clangd?

clangd 11.1.0

**Comment by ray-x** [comment]
I am using clangd as well, 
also tried lua with function like `f(a, b, ...)` 
still not reproduce. It may because your neovim version... Is it updated to latest?

**Comment by lbiaggi** [comment]
Hum which version are you using?
```
nvim --version
NVIM v0.5.0-dev+1353-g0a653f7ab
Build type: RelWithDebInfo
```

**Comment by lbiaggi** [comment]
I just updated my neovim build, and now it's working as expected.
