### ISSUE TITLE
[enhancement] add support to option `floating_window_off_y` as a function

### ISSUE THREAD

**Issue by yao-weijie** [ray-x/lsp_signature.nvim#248]
In current version, it's difficult to avoid conflict between `lsp_signature.nvim` and `nvim-cmp`, especially when the cursor at the top or bottom of window, I found a solution to solve this problem.

- my config:
```lua
local function offsety()
    local linenr = vim.api.nvim_win_get_cursor(0)[1] -- buf line number
    local pumheight = vim.o.pumheight -- my default 10
    local winline = vim.fn.winline() -- line number in the window
    local winheight = vim.fn.winheight(0)

    -- window top
    if linenr < pumheight then
        return pumheight
    end

    -- window bottom
    if winheight - winline < pumheight then
        return -pumheight
    end

    return 0
end

lsp_signature.setup({
    ...

    floating_window = true,
    floating_window_above_cur_line = false,
    floating_window_off_x = 0,
    floating_window_off_y = offsety,

    ...
})
```

- modification
modify `lsp_signature.nvim/lua/init.lua`
![图片](https://user-images.githubusercontent.com/36393630/206346358-c316b4b0-440c-42db-86d7-7cecc2984b5f.png)

- final effect
  - at window top
    
![图片](https://user-images.githubusercontent.com/36393630/206346868-85eebe9d-7b05-4614-b186-9f7b477fdb5b.png)

  - at window bottom
    
![图片](https://user-images.githubusercontent.com/36393630/206347054-efc701eb-a49c-4a95-ab7d-0789a2650949.png)

  - at window middle area
    
![图片](https://user-images.githubusercontent.com/36393630/206347156-7438f8c7-345b-45c4-8d57-5921c6fed2ae.png)

- requirements
  the window is high enough, and it's better not to split horizontal :)

**Comment by ray-x** [comment]
Thanks for your suggestions.
I pushed a commit based on your code snippets.

**Comment by ray-x** [comment]
@yao-weijie 
Could you check if it works for you.
Also when you happy, please share your offset_x/y function setup.

**Comment by yao-weijie** [comment]
I replied the mail but it seems that you didn't received it. :(

The patch works (I used the offset_y function as you put in README). And I think there are some  auxiliary options is important.

```vim
" better to set the two options the same
set scrolloff=10 " 
set pumheight=10 " max height of cmp menu

" lsp_signature option
" if set to false, it may still conflict with cmp at middle of window
floating_window_above_cur_line = true
```
I think there is still some points to improve the floating window experience. Look at the img: 
![图片](https://user-images.githubusercontent.com/36393630/208617778-5fb13163-360a-4801-b3cb-b8293ab15191.png)

If it is possible to pass a parameter to the offset_x/y function that contains the floating window size (especially height) like this? Then I think the signature help will be perfect!

![图片](https://user-images.githubusercontent.com/36393630/208618514-a19e46fb-6e14-4cbd-b598-51565f31707c.png)

**Comment by ray-x** [comment]
I am wondering how you want to pass in the opts?

**Comment by yao-weijie** [comment]
setup{
    floating_window_off_y = function(opts)
       ...
    end
}

the opts contains the signature help window size. Actually I'm not sure of the process of generating the help window. If help window size is calculated before offset_y, then you can pass the size to the offset_y function.

**Comment by ray-x** [comment]
I pushed another change to allow floating_opts been passed to off_x/y. Would you take a look?
