### ISSUE TITLE
Packer fails to update this plugin

### ISSUE THREAD

**Issue by dhruvmanila** [ray-x/lsp_signature.nvim#25]
Packer fails to update this plugin with the following error message:
```
 ✗ Failed to update ray-x/lsp_signature.nvim
  Errors:
    fatal: refusing to merge unrelated histories
    2dfeb79
```

I think this is related to [this comment](https://github.com/wbthomason/packer.nvim/issues/381#issuecomment-849815901) which specifies it will fail if the public branch has been rebased. The feature of allowing unrelated git histories from the side of packer is ongoing.

I also think it's best practice to not rebase a public branch which a lot of people rely on. This will also prevent someone to know which new commits were added since the last update and thus what are the new features/fixes for the plugin.

If rebasing is not the cause of this error, then please ignore this and close it.

**Comment by thesergiomiguel** [comment]
This is also happening with vim-plug, for what it's worth.

**Comment by ray-x** [comment]
Did I run rebase recently? No.

What the hell I did?
I run  `git filter-branch` and  `git gc --prune=now --aggressive` to shrink the git repo size (save around 1MB after those commands)

It seems packer & plug does not allow unrelated history to be merge.  To be frank I have no idea how to solve this issue ATM.

**Comment by ray-x** [comment]
I think some of the hash was missing and I pushed them. But other than that, I do not know how to fix the issue.

**Comment by dhruvmanila** [comment]
Alright, thank you for describing your workflow regarding this plugin. There is a PR in the works on Packer.nvim (https://github.com/wbthomason/packer.nvim/pull/335) to allow unrelated histories, I will forward this issue and your workflow to them so that this can be tested.

Thanks again for taking a look at it, I will close this now.

**Comment by dhruvmanila** [comment]
I just read the official documentation for `git filer-branch` and here's the starting paragraph:

> WARNING
> git filter-branch has a plethora of pitfalls that can produce non-obvious manglings of the intended history rewrite (and can leave you with little time to investigate such problems since it has such abysmal performance). These safety and performance issues cannot be backward compatibly fixed and as such, its use is not recommended. Please use an alternative history filtering tool such as git filter-repo. If you still need to use git filter-branch, please carefully read SAFETY (and PERFORMANCE) to learn about the land mines of filter-branch, and then vigilantly avoid as many of the hazards listed there as reasonably possible.

Ref: https://git-scm.com/docs/git-filter-branch

**Comment by ray-x** [comment]
I did not fully aware of the side effect of filter-branch and simply following a blog post to clean up branches.  Should have been more careful 🧐
