### ISSUE TITLE
Error executing vim.schedule lua callback ... String cannot contain newlines

### ISSUE THREAD

**Issue by RayJameson** [ray-x/lsp_signature.nvim#254]
Hello @ray-x! THanks for your wonderful plugin. I'm having this problem when I use signature help inside of python's [asyncio.gather()][gather]

Some info:
| Action | LSP | lsp_signature.nvim | Result |
|---|---|---|---|
| use `vim.lsp.buf.signature_help()` | [jedi_language_server][jedi]  | disabled | OK ✅ |
| go insert mode or use `vim.lsp.buf.signature_help()`  | [pylsp][pylsp] (`python-language-server`) | enabled | OK ✅ |
| go insert mode or use `vim.lsp.buf.signature_help()` | [jedi_language_server][jedi]  | enabled | ERROR ❌  |

```vim
Error executing vim.schedule lua callback: ...lar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/util.lua:1314: String cannot contain newlines
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...lar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/util.lua:1314: in function 'stylize_markdown'
        ...lar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/util.lua:1572: in function 'open_floating_preview'
        ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.lua:517: in function 'handler'
        ...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

[gather]: https://github.com/python/cpython/blob/main/Lib/asyncio/tasks.py#L721
[jedi]: https://github.com/pappasam/jedi-language-server
[pylsp]: https://github.com/python-lsp/python-lsp-server

I have `lsp_signature.log` for both cases when plugin is enabled but I'm not comfortable sharing them here in open format. I can send them directly to you

**Comment by ray-x** [comment]
Thanks, I pushed a fix fir it. Could you check if it works for you?

**Comment by RayJameson** [comment]
Yes it's OK now, thanks a lot for fast response and fix!
