### ISSUE TITLE
Speical font need?

### ISSUE THREAD

**Issue by laowalter** [ray-x/lsp_signature.nvim#278]
Is there a special font or I can customize it on the red circle position ?

Thx. 

![lsp_signature_q](https://github.com/ray-x/lsp_signature.nvim/assets/16535798/52299e03-32e9-4a7c-8ce4-77d20699b23b)

**Comment by laowalter** [comment]
Got it from the full configuration.

hint_prefix = "🐼 "

**Comment by ray-x** [comment]
It is emoji
I think the terminal need support emoji. otherwise you can config it to nerdfont.
