### ISSUE TITLE
Virtual text only for insert mode and floating window for normal mode

### ISSUE THREAD

**Issue by GGCristo** [ray-x/lsp_signature.nvim#28]
Greetings, I have noticed that this plugin override the default `vim.lsp.buf.signature_help()` and now I wonder if there is any way to have virtual text only while I am typing and trigger the floating window without typing (with keystrokes)?

**Comment by ray-x** [comment]
I do not think it is possible ATM.
Do you accept virtual text only in insert mode, and in normal mode, when you use your keymap to invoke vim.lsp.buf.signature_help() showing the floating window?

**Comment by GGCristo** [comment]
That would be great

**Comment by ray-x** [comment]
It should been fixed in new version. Please update your plugin and give it a try. Thanks!

**Comment by GGCristo** [comment]
Yes, it's perfect, it also works in insert mode. Thanks
