### ISSUE TITLE
Cursor position outside buffer

### ISSUE THREAD

**Issue by tan-wei** [ray-x/lsp_signature.nvim#295]
Use lsp_signature with cmp will cause this:
```
Error executing vim.schedule lua callback: ...vim/lazy/lsp_signature.nvim/lua/lsp_signature/helper.lua:676: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	...vim/lazy/lsp_signature.nvim/lua/lsp_signature/helper.lua:676: in function 'highlight_parameter'
	.../nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:618: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1517: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

And my configuration for lsp_signature is:
```lua
{
  log_path = vim.fn.stdpath "cache" .. "/lsp_signature.log",
  debug = true,
  hint_enable = false,
  handler_opts = { border = "rounded" },
  max_width = 80,
  noice = true,
}

```

**Comment by tan-wei** [comment]
It seems that neovim API returns this error. My neovim version is (nightly):
```
NVIM v0.10.0-dev-1573+gd92dd2a0c05
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
Run "nvim -V1 -v" for more info
```

**Comment by tan-wei** [comment]
Here is the debug log, I've cleaned the previous contents:
[lsp_signature.log](https://github.com/ray-x/lsp_signature.nvim/files/13393118/lsp_signature.log)

**Comment by ray-x** [comment]
I assume you are using latest version  of lsp_signature.
Could you send a rust code snippet i can reproduce the issue? I checked your logs but unfortunately, I  am not familiar with rust and did not find anything useful yet.

**Comment by tan-wei** [comment]
Yes, I use the latest version  of lsp_signature. A simple clean code should help:
```rust
fn test_function(a: i32, b:i32) -> i32 {
  0
}

fn main() {
  test_function(1, 2)
}
```
![图片](https://github.com/ray-x/lsp_signature.nvim/assets/28227509/2221541f-5b16-4c8e-ab22-dc5ea8e9270f)

**Comment by ray-x** [comment]
Looks good to me
<img width="438" alt="image" src="https://github.com/ray-x/lsp_signature.nvim/assets/1681295/89151da7-b1c2-4822-a65f-c676bbebeb10">

I am using same version: NVIM v0.10.0-dev-1573+gd92dd2a0c-Homebrew

Could you set `noice = false,` I does not use noice and it might be they changed something

**Comment by tan-wei** [comment]
OK, after set `noice = false`, it does not happen. So I think your guess is correct.

**Comment by ray-x** [comment]
I may run some test and deprecate `noice` setting
