### ISSUE TITLE
max_width is not working

### ISSUE THREAD

**Issue by krakn-dev** [ray-x/lsp_signature.nvim#296]
### Expected Behavior
Plugin's popup should not exceed 30 characters wide.

### Actual  Behavior
Plugins popup exceeds 30 characters wide.

### Steps to Reproduce
1. Install with packer using the following line
`use "ray-x/lsp_signature.nvim"`.

2. Add these lines to `~/.config/nvim/init.lua`.
```
local cfg = {
    max_width = 30,
    debug = true
}

require "lsp_signature".setup(cfg)

3. Go to Typescript and create an instance of a class
```

### Details
debug mode shows at the beginning it reads the configuration and sets `max_width` to 30, going below shows the value `width` to be 60, which i imagine is the computed value.

**Comment by ray-x** [comment]
It is kind of expected:
```lua
config.max_width = math.max(_LSP_SIG_CFG.max_width, 60)
```
I adjusted it to be 40 
```
config.max_width = math.max(_LSP_SIG_CFG.max_width, 40)
```
and update the doc.
TBH, I do not think it shows anything decent when the size is below 60.

**Comment by krakn-dev** [comment]
you are right it doesn't look too good, but is good to know, really appreciate your response
