### ISSUE TITLE
Overlapping with tabnine's prompt

### ISSUE THREAD

**Issue by ayamir** [ray-x/lsp_signature.nvim#30]
![image](https://user-images.githubusercontent.com/61657399/122790475-ecaef000-d2ea-11eb-8d98-defb885f47ec.png)
You know tabnine's completion is instantly, so its prompt overlaps at  it.

**Comment by ayamir** [comment]
Sorry, I need to configure tabnine. Following is how I fix it:
```lua
-- Compe setup
require'compe'.setup {
enabled = true;
autocomplete = true;
debug = false;
min_length = 1;
preselect = 'enable';
throttle_time = 80;
source_timeout = 200;
resolve_timeout = 800;
incomplete_delay = 400;
max_abbr_width = 100;
max_kind_width = 100;
max_menu_width = 100;
documentation = true;

source = {
	path = true;
	buffer = true;
	calc = true;
	spell = true;
	tags =  true;

	nvim_lsp = true;
	nvim_lua = true;
	treesitter = true;
	vsnip = true;
	tabnine = {
		max_line = 1000;
		max_num_results = 6;
		priority = 5000;
		show_prediction_strength = true;
		sort = false;
		ignore_pattern = '[(]';
		};
	};
}
```

**Comment by ray-x** [comment]
Is it because you setup `priority = 5000;`
tabnine is slow and that is maybe why it appears after the signature popup.

Btw, I add zindex to the lspsignature. Not sure if it helps.

**Comment by ayamir** [comment]
> Is it because you setup `priority = 5000;`
> tabnine is slow and that is maybe why it appears after the signature popup.
> 
> Btw, I add zindex to the lspsignature. Not sure if it helps.

`ignore_pattern = '[(]';`
this line helps in fact.
`tabnine appears after the signature popup`: yes
