### ISSUE TITLE
Doesn't show signature when i open only a single file, works when i open a directory

### ISSUE THREAD

**Issue by gelerum** [ray-x/lsp_signature.nvim#305]
When i open current directory like that `nvim .` it works, but it doesn't when i open a single file `nvim a.py`, signature is just not shown. But hover works and LSP server is enabled. 

I use Lazy.nvim

**Comment by NONVME** [comment]
I have a similar problem

**Comment by ray-x** [comment]
Correct, If lazy loaded, you have to make sure the plugin loaded before lsp client start. Otherwise, on_attach won't hook.
