### ISSUE TITLE
Make floating window pop up only when triggered by a keymapping

### ISSUE THREAD

**Issue by netrolite** [ray-x/lsp_signature.nvim#316]
Hi, I'm wondering if it's possible to make the floating window show up only after it's been triggered by a keymapping instead of automatically whenever I'm inside the parenthesis of a function call. I couldn't find this option in the docs...

Here's my current config:

`plugins/lsp_signature.lua`
```
local map_key = require("utils.map_key")

return {
	"ray-x/lsp_signature.nvim",
	event = "VeryLazy",
	config = function()
		require("lsp_signature").setup({
			hint_enable = false,
			always_trigger = false,
			zindex = 50,
		})

		map_key("<C-y>", function()
			require("lsp_signature").toggle_float_win()
		end)
	end,
}
```

**Comment by ray-x** [comment]
try this:
```lua
 toggle_key = nil, -- toggle signature on and off in insert mode,  e.g. toggle_key = '<M-x>'
```

**Comment by netrolite** [comment]
this didn't work, but don't worry, i forked this repo, changed the code a bit and now it works they way i wanted it to.
