### ISSUE TITLE
failed get highlight parameter nil nil

### ISSUE THREAD

**Issue by doums** [ray-x/lsp_signature.nvim#32]
Hi,

I use this config
```
local signature_help_cfg = {
  bind = true,
  doc_lines = 2,
  floating_window = true,
  hint_enable = false,
  hi_parameter = 'Constant',
  max_height = 4,
  max_width = 80,
  handler_opts = {border = 'none'},
}
```
Constant highlight group is
```
:hi Constant
Constant       xxx gui=bold guifg=#C5656B
```
When I write function parameter, the window with the signature help shows up, but I get no current parameter highlight and an error spawn `failed get highlight parameter nil nil`.

**Comment by ray-x** [comment]
This issue is not caused by highlight group. The debug message may be confusing, I will change that.
What is your lsp. And what is the function signature looks like:
Would be great to send me the code that can reproduce the issue you saw.
e.g.
```
  int function_name(int par1,  string par2)
```

**Comment by doums** [comment]
The server is `rust-analyzer`. You can reproduce the bug with the following:
Init a rust project
```
cargo init test
cd test
```
open `main.rs` and observe the bug
```
fn test_signature(a: i32, b: i32, c: i32) -> i32 {
    a + b - c
}

fn main() {
    test_signature(1, 2, 3); // complete params here
}
```

**Comment by ray-x** [comment]
either fixed or not reproduce
my vimrc 
```
" Note: run PlugUpdate/Install first
set termguicolors
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug '/Users/ray.xu/github/lsp_signature.nvim'

Plug 'ray-x/aurora'

call plug#end()

lua <<EOF
require'lspconfig'.rust_analyzer.setup{}
require'lsp_signature'.on_attach({log_path = "/Users/ray.xu/tmp/sig.log", debug = true})


EOF

set mouse=a
colorscheme aurora
```
https://user-images.githubusercontent.com/1681295/123421435-2be98380-d600-11eb-98ee-54c7ca100dbe.mov

**Comment by doums** [comment]
Hmm, for whatever reason, I can't reproduce the bug anymore. All work well now. I close the issue.
