### ISSUE TITLE
vim.tbl_flatten is deprecated in Neovim 0.10

### ISSUE THREAD

**Issue by kyoh86** [ray-x/lsp_signature.nvim#330]
see: https://neovim.io/doc/user/deprecated.html#vim.tbl_flatten()

https://github.com/ray-x/lsp_signature.nvim/blob/2ec2ba23882329c1302dff773b0d3620371d634f/lua/lsp_signature/init.lua#L20

We should use `vim.iter({...}):flatten:totable()` instead.

**Comment by ray-x** [comment]
Closed in latest version.
