### ISSUE TITLE
Malformed pattern

### ISSUE THREAD

**Issue by sQVe** [ray-x/lsp_signature.nvim#37]
👋🏼 

I'm primarily using `javascript` and `typescript` and I'm seeing this quite often:

![image](https://user-images.githubusercontent.com/2284724/123643154-659ad400-d824-11eb-8bea-aea7c5f9e6e3.png)

I can replicate it with the default config and writing `console.log('foo',`.

**Comment by ray-x** [comment]
Thanks for your report
This issue is caused by failing to handle javascript array. It was fixed in latest version.

**Comment by sQVe** [comment]
Verified working on my machine after update. Thanks for the quick fix. 🎉 

Closing.
