### ISSUE TITLE
Not changing selected param as I type

### ISSUE THREAD

**Issue by jared-mackey** [ray-x/lsp_signature.nvim#38]
👋🏻 

I am using this with ElixirLS and LSP and as I type new parameters to the function it is not moving with it. Also, the panda seems to disappear when moving to the second param. See example screenshot.  Happy to help debug/fix the issue, just not sure where to start. Thanks!

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/10620022/123706782-f7efa780-d825-11eb-9c8c-82b227abdcc7.png">

**Comment by jared-mackey** [comment]
Also, it gets weird with nested functions. It keeps the signature of the outermost function and doesn't pop it for the inner func. 

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/10620022/123707181-8cf2a080-d826-11eb-993b-4d0f101c8f97.png">

**Comment by ray-x** [comment]
Thanks for the report.
I had never used Elixir / ElixirLS before. So I think there might be something special about ElixirLS or Elixir that my plugin can not handle.
Could you send me:
1) the basic vimrc setup that enables ElixirLS and lsp_signature
2) the code snippets (e.g. some function definitions and how to call those functions so that can reproduce this issue)

**Comment by jared-mackey** [comment]
Yes. Here is the steps to create a new mix project and create the code.

```bash
mix new hello_world
cd hello_world
```

Then replace `lib/hello_world.ex` with this.

```elixir
defmodule HelloWorld do
  @spec say_hello(name :: binary(), age :: integer) :: nil
  def say_hello(name, age) do
    IO.puts("Hello, my name is #{name}. I am #{age} years old.")
    nil
  end

  def test() do
    say_hello("Jared", 28)
  end
end
```

I personally clone elixir-ls and install it manually. I am not sure if there is easier steps for this but this is what I'd do.

```bash
git clone git@github.com:elixir-lsp/elixir-ls.git
cd elixir-ls
git checkout v0.7.0
MIX_ENV=prod mix do deps.get, compile, elixir_ls.release -o ./rel/
```

Then here is my LSP config.

`plugins.lua`
```lua
  use {
    'hrsh7th/nvim-compe',
    config = function()
      require'compe'.setup {
        enabled = true,
        autocomplete = true,
        debug = false,
        min_length = 1,
        preselect = 'enable',
        throttle_time = 80,
        source_timeout = 200,
        incomplete_delay = 400,
        max_abbr_width = 100,
        max_kind_width = 100,
        max_menu_width = 100,
        documentation = true,
        source = {
          path = true,
          buffer = true,
          calc = true,
          nvim_lsp = true,
          nvim_lua = true,
          vim_dadbod_completion = true,
          vsnip = true
        }
      }
    end
  }
  use {
    'neovim/nvim-lspconfig',
    config = function() require('lsp') end,
  }
  use {
    'ray-x/lsp_signature.nvim',
    config = function() require('lsp_signature').on_attach() end,
  }
```


`lsp.lua`
```lua
vim.cmd('packadd nvim-lspconfig')

local nvim_lsp = require'lspconfig'
local configs = require'lspconfig/configs'
local protocol = require'vim.lsp.protocol'

local capabilities = protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

-- LSP SERVER CONFIGURATION
-- ===================================================================
nvim_lsp.elixirls.setup{
  capabilities = capabilities,
  on_attach = function()
    require('lsp_signature').on_attach()
  end,
  cmd = {
    vim.loop.os_homedir() .. "$PATH_TO_ELIXIR_LS/rel/language_server.sh"
  },
  settings = {
    elixirLS = {
      dialyzerEnabled = true;
    }
  }
}
```

LMK if I can help. Thank you so much for looking at this!

**Comment by ray-x** [comment]
Hi, @jared-mackey 
I can reproduce the issue locally and it seems to be a defect of ElixirLS.  And you will need to submit an issue for ElixirLS.

As a lsp server. It should provide `triggered_character` so lsp client will know when to display the signature. What I got from ElixirLS is:
   signature_help_trigger_characters = { "(" },         
and 
   signatureHelpProvider.triggerCharacters=nil;    

This means signature will only be triggered after "(". 
I think signatureHelpProvider.triggerCharacters should be {"(", ","} . As it is for other lsp server.

A workaround for you ATM (before ElixirLS fix this issue) is set

require('lsp_signature').on_attach({extra_trigger_chars={","}})

**Comment by jared-mackey** [comment]
Awesome. Thank you!

**Comment by jared-mackey** [comment]
The PR to ElixirLS confirms it working properly now. Thanks again for digging in and pointing me the right way!

**Comment by ray-x** [comment]
Great! In that case, you do not need the extra_trigger hack.

**Comment by jared-mackey** [comment]
I'm curious though, wouldn't commas count as a retrigger? I see in the protocol spec `retriggerCharacters` as a server capability. Although I don't believe ElixirLS currently supports retriggers.

**Comment by ray-x** [comment]
Not all lsp server support retrigger.
For retrigger, it is a dynamic response and it was sent when signature already present. Only a few lsp support this.  It was designed when signature changed or document changed when the signature is activate. Please be noted that all triggered characters are countered as a re-trigger characters.
Please check this document: https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp
