### ISSUE TITLE
Signature help only activating on the first file opened.

### ISSUE THREAD

**Issue by stevenhay** [ray-x/lsp_signature.nvim#41]
The plugin is working fine on the first file opened:
![image](https://user-images.githubusercontent.com/26744309/124383765-23f7a680-dcc6-11eb-9f7b-c6ee9b2c0209.png)

but opening a new file, whether via Telescope or :e, it stops working:
![image](https://user-images.githubusercontent.com/26744309/124383830-6de08c80-dcc6-11eb-82b9-cccdc550ea64.png)

1. `lua vim.lsp.buf.signature_help()` shows the signature on the second file.
2. `lua require'lsp_signature'.signature()` does not.
3. Manually running `require "lsp_signature".on_attach()` on the second file fixes the issue.

I have this section in my init.vim file:
```
Plug 'ray-x/lsp_signature.nvim'

lua << EOF
  require'lsp_signature'.on_attach({
    extra_trigger_chars = {"(", ","}
  })
EOF
```

I've tried replacing it with simply `require'lsp_signature'.on_attach()` but that also doesn't work. It seems the on_attach isn't being called for new files being opened?

I've also removed lspsaga to see if that's the issue but the problem remains.

**Comment by ray-x** [comment]
Thanks for reporting this issue.

I think you may need to do this as mentioned in README.md:

local golang_setup = {
  on_attach = function(client, bufnr)
    ...
    require "lsp_signature".on_attach()  -- Note: add in lsp client on-attach
    ...
  end,
  ...
}

**Comment by stevenhay** [comment]
That worked! Thank you for the fix and for the amazing plugin. 

I never tried that as I wasn't sure what Packer was and I didn't think I was using it, it seemed like an alternative plugin loader and so I assumed it was a different issue :(

**Comment by ray-x** [comment]
You are right. It is not related to Packer... Thanks for pointing that out. The document is a bit outdated.

The plugin is attached per-buffer.  So should run plugin attach inside lsp on_attach or each time you open a buffer.
