### ISSUE TITLE
Solargraph: .vim/bundle/lsp_signature.nvim/lua/lsp_signature.lua:168: attempt to get length of field 'parameters' (a nil value)

### ISSUE THREAD

**Issue by renatolond** [ray-x/lsp_signature.nvim#42]
Build info:
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
```

I have lspconfig setup with https://github.com/hrsh7th/nvim-compe and `solargraph`
With a ruby script like so:

```
# frozen_string_literal: true

puts()
```

Trying to see the signature for puts returns
```
Error executing vim.schedule lua callback: ...ond/.vim/bundle/lsp_signature.nvim/lua/lsp_signature.lua:168: attempt to get length of field 'parameters' (a nil value)
```

I tried positioning the cursor after the `(` and then doing `lua require'lsp_signature'.signature()`, and it gives me the same error.

**Comment by mortezadadgar** [comment]
facing exact same issue with configured solargraph

**Comment by ray-x** [comment]
Has some fix for this.
But FYI, solargraph does support active parameter. The LSP does not event provide parameter... So the plugin can only show signature without highlight.
