### ISSUE TITLE
Why are we manually attaching?

### ISSUE THREAD

**Issue by ahmedkhalf** [ray-x/lsp_signature.nvim#43]
The following snippet of code is what I use on my plugin lsp-rooter to attach automatically without having to attach it on the lspconfig config.

```lua
local on_attach = function(client, bufnr)
  -- Attach logic goes here
end
```
```lua
local _start_client = vim.lsp.start_client
vim.lsp.start_client = function(lsp_config)
  if lsp_config.on_attach == nil then
    lsp_config.on_attach = on_attach
  else
    local _on_attach = lsp_config.on_attach
    lsp_config.on_attach = function(client, bufnr)
      on_attach(client, bufnr)
      _on_attach(client, bufnr)
    end
  end
  return _start_client(lsp_config)
end
```
Would be great to stop the manual thing, and use the solution provided instead.

**Comment by ray-x** [comment]
Thanks for the suggestion.
I updated the codes and added `setup(cfg)` function using `start_client`.  I will test it a few days before I update the document.

**Comment by ray-x** [comment]
Closing this. As document updated. You can use setup() to initialize the plugin.
