### ISSUE TITLE
Weird behavior with Tabnine Compe and pmenu overlay

### ISSUE THREAD

**Issue by danielnehrig** [ray-x/lsp_signature.nvim#45]
sometimes signature triggers sometimes not
this only happens with tabnine suggestions
see attached video:

https://user-images.githubusercontent.com/4050749/125195936-36d72180-e258-11eb-8272-122c2b1fa00a.mp4

**Comment by ray-x** [comment]
Yes. This behavior has been there for some time. I add zindex to my code but still dose not solve this issue. The thing is compe seems always take priority again other float windows.

**Comment by ray-x** [comment]
@danielnehrig 
If you are using latest neovim. This issue should been fixed... Can you verify that?

**Comment by danielnehrig** [comment]
i will check it out i'll report back

**Comment by danielnehrig** [comment]
problem does not occur anymore with pum and floating signature window
pum has priority
would be nice to have some kind of setting to say that if you enter "(" to trigger signature that signature has priority and pum closes

**Comment by ray-x** [comment]
Great.
Thanks for the suggestion. I will check how to do that.

**Comment by ray-x** [comment]
There is a new setup 
```lua
    require"lsp_signature".setup({
      floating_window_above_first = true,
    })
```

That will allow the floating always above the current line.  Which will solve the overlap issue you are experiencing. Please check if it works.

**Comment by 616b2f** [comment]
@ray-x it solves the issue, at least for me, thank you
