### ISSUE TITLE
signature show floating window(arguments) on switching back from a tab or buffer

### ISSUE THREAD

**Issue by mortezadadgar** [ray-x/lsp_signature.nvim#47]
this only occurs when the cursor is on a function argument and the only way to get rid of the floating window is to enter insert mode
I can record a video if it's not clear enough

**Comment by ray-x** [comment]
Thanks for submitting the issue.
Please also include the LSP you are using, code snippets you are editing.
I did not see similar behavior before. Are there keybinding to trigger this?   A minium vimrc and screen recording will be very helpful. Thanks!

**Comment by mortezadadgar** [comment]
here's a video illustring the issue this only happens if I try to open a file and switch back to last buffer

https://user-images.githubusercontent.com/27911493/127205316-8d37e85f-d4cf-43e4-bc1e-fbdb096cd4b0.mp4

**Comment by mortezadadgar** [comment]
@ray-x any idea?

**Comment by ray-x** [comment]
I can not reporduce the issue.

https://user-images.githubusercontent.com/1681295/128618666-fa2653f7-96b2-4761-9299-a7781ca41ed4.mov

**Comment by mortezadadgar** [comment]
> I can not reporduce the issue.
> sig_issue47.mov

It doesn't seem you're switching back to last buffer that is opened by telescope with `CTRL-^ `

**Comment by ray-x** [comment]
I am using CTRL-I/CTRL-O to jump back. 
Using CTRL-^ does not make any difference.

**Comment by mortezadadgar** [comment]
Ok it seems your plugin has conflicts with LuaSnip

**Comment by mortezadadgar** [comment]
@ray-x it's only reproducible with lazy loading on InsertEnter event [minimal config](https://pastebin.com/ifBYfbcy)
