### ISSUE TITLE
Configuration is not read if signature_help handler defined

### ISSUE THREAD

**Issue by fitrh** [ray-x/lsp_signature.nvim#49]
If i have this handler in my lsp configuration
```lua
["textDocument/signatureHelp"] = vim.lsp.with(
  vim.lsp.handlers.signature_help, {
    border = "rounded"
  }
)
```
the configuration of this plugin is not read, instead it is using the default one.

Is this expected ?

**Comment by ray-x** [comment]
You will have to provide a border array.
ATM the plugin only support `single` and `double`.  They are predefined:

local double = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"}
local single = {"╭", "─", "╮", "│", "╯", "─", "╰", "│"}

You can provide a border with array format to border like this:
```
  vim.lsp.handlers.signature_help, {
    border =  {"╭", "─", "╮", "│", "╯", "─", "╰", "│"}
  }
```

**Comment by fitrh** [comment]
Yes, i know it, i have looked into the source code, the problem is, whenever i define the signature_help handler, then the plugin not respect the configuration, here what is my `config` looks like
```lua
local config = {
  bind = true,
  floating_window = false,
  hint_prefix = " ",
  hint_scheme = "LspDiagnosticsDefaultHint",
  hi_parameter = "LspSignatureActiveParameter",
  extra_trigger_chars = { "(", "{", "," },
}
```
And the expected result is something like this
![20210723_143559_full](https://user-images.githubusercontent.com/55179750/126746335-063a55da-b5d5-4864-af62-9664fa777bdc.jpg)
But if i define `signature_handler` like this
```lua
["textDocument/signatureHelp"] = vim.lsp.with(
  vim.lsp.handlers.signature_help, {
    border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"}
  }
)
```
The result become like this
![20210723_143526_full](https://user-images.githubusercontent.com/55179750/126746629-85261e62-40f4-4b4d-9c44-082af597dafb.jpg)

As you see, lsp_signature use the border from that handler but not use the configuration from `config`

**Comment by ray-x** [comment]
Well, you can not init lsp_signature like this:
```
["textDocument/signatureHelp"] = vim.lsp.with(
  vim.lsp.handlers.signature_help, {
    border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"}
  }
)
```
This will just use default signature_help provided by `lsp_config`
You have to do this:
```
require "lsp_signature".setup({
    bind = true,
    border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"},
    floating_window = false,
    hint_prefix = " ",
  })
```

**Comment by fitrh** [comment]
> Well, you can not init lsp_signature like this:
> 
> ```
> ["textDocument/signatureHelp"] = vim.lsp.with(
>   vim.lsp.handlers.signature_help, {
>     border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"}
>   }
> )
> ```

Exactly, i do not initialize lsp_signature like this, but i have this in my  lsp `handlers` key, and because of that, even if i pass this configuration
> This will just use default signature_help provided by `lsp_config`
> You have to do this:
> 
> ```
> require "lsp_signature".setup({
>     bind = true,
>     border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"},
>     floating_window = false,
>     hint_prefix = " ",
>   })
> ```
lsp_signature won't read them

**Comment by fitrh** [comment]
For example, this is my `clangd` config
```lua
lspconfig.clangd.setup({
  on_attach = function(client, bufnr)
    require("lsp_signature").on_attach({
        bind = true,
        floating_window = false,
        hint_prefix = " ",
        hint_scheme = "LspDiagnosticsDefaultHint",
        hi_parameter = "LspSignatureActiveParameter",
        extra_trigger_chars = { "(", "{", "," },
      })
  end,
  capabilities = require("lsp.capability"),
  handlers = {
    ["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
      }
    ),
    ["textDocument/signatureHelp"] = vim.lsp.with(
      vim.lsp.handlers.signature_help, {
        border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"},
      }
    ),
  }
})
```
The config expected to display lsp_signature with no floating window, but the result is what you see at this
> 
> The result become like this
> ![20210723_143526_full](https://user-images.githubusercontent.com/55179750/126746629-85261e62-40f4-4b4d-9c44-082af597dafb.jpg)
> 
It's become normal if i remove the `vim.lsp.handlers.signature_help` from my handlers list

**Comment by fitrh** [comment]
So, is this expected behaviour ? we can not define `vim.lsp.handlers.signature_help` if we want to use lsp_signature config ?

**Comment by ray-x** [comment]
If you are using Clangd, Here is what you config should look like

```lua
lspconfig.clangd.setup({
  on_attach = function(client, bufnr)
    require("lsp_signature").on_attach({
        bind = true,
        floating_window = false,
        hint_prefix = " ",
        hint_scheme = "LspDiagnosticsDefaultHint",
        hi_parameter = "LspSignatureActiveParameter",
        extra_trigger_chars = { "(", "{", "," },
      })
  end,
  capabilities = require("lsp.capability"),
  handlers = {
    ["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
      }
    )
}
```

You do not need this:
```
    ["textDocument/signatureHelp"] = vim.lsp.with(
      vim.lsp.handlers.signature_help, {
        border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"},
      }
    ),
```
The reason is that you hook the signature twice and the second one will override the first. That is why the config is not working correctly.
The plugin allows  ["textDocument/signatureHelp"] to be overrided and will call the overriding signature function instead of the signature function provided by the plugin.

**Comment by fitrh** [comment]
> The reason is that you hook the signature twice and the second one will override the first. That is why the config is not working correctly.
> The plugin allows ["textDocument/signatureHelp"] to be overrided and will call the overriding signature function instead of the signature function provided by the plugin.

Yes, I think so, I just wanted to know if we can define `["textDocument/signatureHelp"]` with a border, and this plugin only takes the border without ignoring all its other configurations. but it looks like this plugin ignores the configuration.

**Comment by ray-x** [comment]
In fact if you set
``` 
["textDocument/signatureHelp"] = vim.lsp.with(
      vim.lsp.handlers.signature_help, {
        border = {"╔", "═", "╗", "║", "╝", "═", "╚", "║"},
      }
    ),
```
This means you hook signature help to  `vim.lsp.handlers.signature_help` and the setting was set to `vim.lsp.handlers.signature_help`. Not the plugin.
This is a feature requested by lspsaga user who wants to hook the lspsaga floating window to lsp_signature.

**Comment by fitrh** [comment]
> The reason is that you hook the signature twice and the second one will override the first. That is why the config is not working correctly.
> The plugin allows ["textDocument/signatureHelp"] to be overrided and will call the overriding signature function instead of the signature function provided by the plugin.

Yes, I think so, I just wanted to know if we can define `["textDocument/signatureHelp"]` with a border, and this plugin only takes the border without ignoring all its other configurations. but it looks like this plugin ignores the configuration
