### ISSUE TITLE
Does not work with omnisharp

### ISSUE THREAD

**Issue by insidewhy** [ray-x/lsp_signature.nvim#50]
The equivalent VS Code feature works with the same version of omnisharp, but for lsp_signature I get nothing.

I'm installing omnisharp via lsp_install:

```vim
require'lspinstall'.setup()
```

then `:LspInstall csharp` to install the csharp language server (followed by restarting neovim).

Setting up my csharp lsp config the same way I'm setting up tsserver. Using treesitter for typescript and C#. Everything works great when it comes to typescript and csharp completion, but lsp_signature is only working for typescript.

The following shows the signature:

```vim
lua vim.lsp.buf.signature_help()
```

But the following does not:

```vim
lua require'lsp_signature'.signature()
```

Running this manually makes no difference:

```vim
lua require "lsp_signature".on_attach()
```

(although that's already set up in my configuration anyway).

I tried disabling my entire neovim config except for `nvim-lspconfig`, `nvm-lspinstall` and `lsp_signature` but it still didn't work (but continued to work for typescript).

**Comment by insidewhy** [comment]
After a bunch of debugging I figured it out, thanks to your great docs and readable code.

omnisharp returns the following trigger_chars:

```
signature_help_trigger_characters = <10>{ ".", "?", "[" }
```

This is incorrect, I fixed it via:

```lua
require "lsp_signature".on_attach {
  extra_trigger_chars = { "(", ",", "<" },
}
```

**Comment by insidewhy** [comment]
I've added a fix to the language server that will allow it to work out of the box: https://github.com/OmniSharp/omnisharp-roslyn/pull/2193

**Comment by ray-x** [comment]
@insidewhy 
Thanks for submitting PR to OmniSharp.
