### ISSUE TITLE
Getting "failed get highlight parameter 0 0"

### ISSUE THREAD

**Issue by henrique-ezcater** [ray-x/lsp_signature.nvim#51]
Hello!

I am trying get highlight of the parameters in the pop-up, but as soon as I type `(` to provide the parameters I get the error `failed get highlight parameter 0 0`.
This is using `pyright` and the following python code can be used to reproduce it:

```python
import os

def bla(a: int, b: int, c: int, d: int):
    print(f"a #{a}, b #{b}, c #{c}, d #{d}")

def x(a):
    print("hey! %s" % a)
    bla(
```

Here is a screenshot:

![image](https://user-images.githubusercontent.com/77297632/126906444-c6e439e0-0602-42b9-a083-5d5de9a82e3c.png)

Here is the debug output:

```
שׁ  |1: insert enter
שׁ  |1: insert enter
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: signature triggered
שׁ  |1: sig result |2: {
  activeParameter = 4,
  activeSignature = 0,
  signatures = { {
      activeParameter = 0,
      label = "(a: int, b: int, c: int, d: int) -> None",
      parameters = { {
          label = { 1, 7 }
        }, {
          label = { 9, 15 }
        }, {
          label = { 17, 23 }
        }, {
          label = { 25, 31 }
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = "    bla(",
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", ")" }
}

שׁ  |1: no next param
שׁ  |1: md lines |2: { "```python", "(a: int, b: int, c: int, d: int) -> None", "```" }

שׁ  |1: label: |2: (a: int, b: int, c: int, d: int) -> None |3: 0 |4: 1 |5: 4 |6: {
  activeParameter = 0,
  label = "(a: int, b: int, c: int, d: int) -> None",
  parameters = { {
      label = { 1, 7 }
    }, {
      label = { 9, 15 }
    }, {
      label = { 17, 23 }
    }, {
      label = { 25, 31 }
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "BufHidden", "InsertLeavePre" },
  focus_id = "textDocument/signatureHelplsp_signature795",
  line_to_cursor = "    bla(",
  max_height = 12,
  max_width = 120,
  offset_x = -1,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", ")" },
  zindex = 200
}

שׁ  |1: extmark |2: 0 |3: 0
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
שׁ  |1: timer start
```

From a quick glance at the code, I couldn't figure out the issue. I got here: 
https://github.com/ray-x/lsp_signature.nvim/blob/78af1399d0e7a85152d4f75b9ce0c20286735d6e/lua/lsp_signature_helper.lua#L114

Can't really tell why that is returning nil? Or perhaps I am following the code incorrectly. My lua skillz aren't that great.

Any ideas?

Thanks!

**Comment by tiagovla** [comment]
I have the same issue.

**Comment by ray-x** [comment]
What LSP you are using?

**Comment by tiagovla** [comment]
In my case pyright with built in neovim LSP.

**Comment by henrique-ezcater** [comment]
Same here, using pyright

**Comment by ray-x** [comment]
I think this issue is caused by pyright. 

The log you posted:
```lua
{
  activeParameter = 4,
  activeSignature = 0,
  signatures = { {
      activeParameter = 0,
      label = "(a: int, b: int, c: int, d: int) -> None",
      parameters = { {
          label = { 1, 7 }
        }, {
          label = { 9, 15 }
        }, {
          label = { 17, 23 }
        }, {
          label = { 25, 31 }
        } }
    } }
}
```

Check this:
```
  activeParameter = 4,
  activeSignature = 0,
```

`activeSignature=0`, this means it is Zero-based numbering. But `activeParameter=4`. This is incorrect. I think what pyright means is `activeParameter=3`

**Comment by henrique-ezcater** [comment]
Isn't the `activeParameter` outside of the `signatures` the count of parameters? I think that the correct would be for the code to be using the internal `activeParameter` for indexing then, no?

**Comment by henrique-ezcater** [comment]
I am thinking that perhaps this here needs to be changed:

https://github.com/ray-x/lsp_signature.nvim/blob/78af1399d0e7a85152d4f75b9ce0c20286735d6e/lua/lsp_signature_helper.lua#L95-L96

The code there perhaps should read:

```lua
  local activeParameter = signature.activeParameter + 1
```

**Comment by ray-x** [comment]
Different LSP sending activeParameter back in slight different way and that is why 
```lua
local activeParameter = result.activeParameter or signature.active_parameter 
                             or signature.activeParameter
```
But activeParameter=4 is incorrect. All LSP activeParameter is 0 based.

**Comment by henrique-ezcater** [comment]
I had success replacing that line with:

```lua
  local activeParameter = signature.activeParameter or signature.active_parameter or result.activeParameter
```

It works now with pyright.

With `solargraph` the issue seems to be on the `solargraph` side as the response from solargraph does not contain the `signatures` object. I will open an issue with them.

**Comment by henrique-ezcater** [comment]
I just checked the spec for `signatureHelp`, here is that it says:

```
	/**
	 * The index of the active parameter.
	 *
	 * If provided, this is used in place of `SignatureHelp.activeParameter`.
	 *
	 * @since 3.16.0
	 */
	activeParameter?: uinteger;

```

So the code should really read the way I pasted in my previous reply:

```lua
  local activeParameter = signature.activeParameter or signature.active_parameter or result.activeParameter
```

The `activeParameter` inside the `signature` object has precedence over the one outside of it in the `result` object. Does that make sense?

Here is the link to the documentation: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#signatureHelp

**Comment by ray-x** [comment]
I do not know why the designer decided to send an out of range index to indicate it to be 0 in 3.17 .  What a nice pitfall!

I pushed my changes.

**Comment by henrique-ezcater** [comment]
I checked the changes there, and I think you should still change the order for setting the `activeParameter` as I mentioned above. The `signature.activeParameter` should have precedence over `result.activeParameter`.
With your change, if you have a function with let's say, 3 arguments, and you try to add a 4th argument to it, the first argument gets re-highlighted:

![image](https://user-images.githubusercontent.com/77297632/127007215-f22639e1-2e6f-48f1-8c11-394a06df5627.png)

**Comment by ray-x** [comment]
@henrique-ezcater 
I strictly adhere  to spec of 3.17

activeParameter: 
	 * If omitted or the value lies outside the range of `signatures[activeSignature].parameters`
	 * defaults to 0 if the active signature has parameters. 
 
And I also override activeParameter with signature.activeParameter if it present:

``` lua
  if result.activeParameter ~= nil and result.activeParameter < #signature.parameters then
    activeParameter = result.activeParameter
  else
    activeParameter = 0
  end

  if signature.activeParameter ~= nil then
    activeParameter = signature.activeParameter
  end

```

I am avoiding doing hacky things for a specific LSP.  I can do a special fix for pyright when I know the exact behaviour so I can know the fix will not break other LSP.

**Comment by henrique-ezcater** [comment]
Yeah, I've checked the code again and I noticed I had missed part of the logic. Seems like this is in accordance to the spec.
Thanks for the fix!
