### ISSUE TITLE
Signature window occludes popup menu for completion as well as text

### ISSUE THREAD

**Issue by wookayin** [ray-x/lsp_signature.nvim#53]
Please see this screenshot:

![image](https://user-images.githubusercontent.com/1009873/127327915-0ea6b026-5bfd-4713-a157-5e27f1ad7b6f.png)

when LSP signature popup window is open, it will occlude and hide the popup menu triggered for completion.

Here is what would be shown if there were no signature displayed:

![image](https://user-images.githubusercontent.com/1009873/127327990-f3c0b4dd-5d2c-4612-a26e-730a3321c51a.png)

Similarily, the signature window will hide the main editor itself when the cursor moves to a position that overlaps the signature window:

![image](https://user-images.githubusercontent.com/1009873/127328324-48dcc5eb-c31a-4537-b189-5637c07f1de6.png)

**Comment by ray-x** [comment]
Yes. I think it is a designed behaviour so signature help will be on top. Please see refer to this issue https://github.com/ray-x/lsp_signature.nvim/issues/30
I am not sure if other plugins support z-index. If they did we can always configure the layers to the order you like.

**Comment by wookayin** [comment]
**Regarding conflict with popup menu**:

When LSP signature is shown on a floating window, completion (popup menu) should appear on top of the signature window. This is the behavior that makes sense because one would want to see completions for the current function argument.

The popup menu in neovim has z-index of 100, so I suggest lsp_signature's z-index **should be less than 100**. Setting `config.zindex = 99` would give me a desired behavior. I think it would be ideal to make this configurable rather than having a hard-coded number.

**Regarding multi-line function call:**
This has nothing to do with popup menu or other plugin. When the cursor moves, the signature window should be moved as well (or just close the window so it can be re-opened again). This is a behavior of all other sensible IDE would have.

Any thoughts?

**Comment by ray-x** [comment]
Code updated. I added an option for `zindex`
Regarding 2nd. There is an option for that:   ` fix_pos = true, -- fix floating_window position`

Check if they work for you.

**Comment by wookayin** [comment]
Thanks @rayx for adding the new option. 

The `fix_pos` option also works for me -- the floating window positions get updated whenever cursor moves so it doesn't hide the text editor. Why not having this as a default?

**Comment by ray-x** [comment]
Well, to be frank, there are lots of requirements asking the floating window to be stable/fix. Personally, I feel it is less distractive as well.

**Comment by shlomocarmeter** [comment]
Hey, just wanted to ask, can the signature be above the line of code instead of below?

**Comment by ray-x** [comment]
The floating windows is adaptive and it based on your current line is in the bottom part of the screen or upper part.

**Comment by shlomocarmeter** [comment]
Can this be configured? maybe allow the user to pick always above, always below or adaptive as currently is the case?

**Comment by ray-x** [comment]
Yes, you can config it with `zindex` value. Also a keymap to toggle signature on and off. Please check readme.

**Comment by shlomocarmeter** [comment]
@ray-x Thanks for replying. I've read the readme before asking and know about zindex.
What I meant was that the signature should appear above the line let's say on the previous line (not the stack order of floating windows).

Sorry if I didn't make myself clear.

**Comment by ray-x** [comment]
It is kind of hard to do that. The major problem is the position is calcuted by nvim API  `make_floating_popup_options(width, height, opts)`
Also, Please be noted that the PUM can also be above the current line. So make floating window below current can not be guaranteed.

**Comment by shlomocarmeter** [comment]
@ray-x I understand. Big thanks for the quick replies and your patience. I'll try looking into nvim api and figure something out. Thanks

**Comment by ray-x** [comment]
I pushed an branch 

https://github.com/ray-x/lsp_signature.nvim/tree/dev

It is kind of ugly, but it will put the floating above current line if you set `  floating_window_above_first = true, `

**Comment by ray-x** [comment]
No worries. I

**Comment by shlomocarmeter** [comment]
@ray-x Thanks man! I'll try it and see how it goes

**Comment by shlomocarmeter** [comment]
@ray-x Great work! This is exactly what I needed. Cheers!

**Comment by ray-x** [comment]
Thanks for verifying that. I will test it for a few days before merging it back.

**Comment by ray-x** [comment]
Feature merged to master.  can be enable by setup `floating_window_above_first = true,`
