### ISSUE TITLE
[phpactor]: Highlight wrong keyword on matching string 

### ISSUE THREAD

**Issue by shaksiper** [ray-x/lsp_signature.nvim#55]
If the same keyword came before the current parameter's name such as string $foo, string $string
first matching keyword is highlighted (string before $foo in above example)

![crop 1](https://user-images.githubusercontent.com/79347616/127798411-7ef84cb8-84e3-4d7e-b090-783e9c55b5cc.png)
![crop 2](https://user-images.githubusercontent.com/79347616/127798414-7ac6ea09-de67-4335-9501-3ae167735aac.png)

`... string $string, ... ` is never highlighted

**Comment by ray-x** [comment]
what PHP lsp you are using?

**Comment by shaksiper** [comment]
Sorry I wasn't very detailed.

I'm using Nvim 0.5 with ALE and Compe
And phpactor as the PHP language server

**Comment by shaksiper** [comment]
PHP variable starting character "$" might be the reason. Because it breaks the signature window too.
Basically as soon as I put $, the windows just disappears.
As the screenshots show, $ char is not even highlighted. So matching pattern probably just ignores it.

**Comment by ray-x** [comment]
My codes should have cover '$'. But I need to test it.

**Comment by ray-x** [comment]
I tried but `phpactor` failed to work. I got a 255 error.

I also tested intelephense, it works correctly with `$`

Please enable the logs by:

```
  require "lsp_signature".setup({
            log_path = "/your_log_path/sig.log",
            debug = true,
  })
```
And attach the logs `sig.log`

**Comment by shaksiper** [comment]
I'll try to in the first opportunity.

**Comment by dirn** [comment]
I'm not sure if this is related, but using Neovim's builtin client and the Jedi language server, I've noticed a similar problem with Python. When the name of the argument appears elsewhere earlier in the signature, the highlight is in the wrong place.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/168109/128369996-a75688d2-0350-42e3-ac64-ccf12a5c8a26.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/168109/128370077-4489f22b-ec4f-4df2-8fb2-b9ea50f7937f.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/168109/128370711-d3bf18fd-66aa-4e7a-94e5-ee7da1f959ec.png">


Whereas if the argument's name doesn't appear anywhere else before it, it works as expected.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/168109/128370332-4de8ba84-8dd6-447c-9c08-7b9804ca9e28.png">
