### ISSUE TITLE
Empty lines in signature

### ISSUE THREAD

**Issue by HansPinckaers** [ray-x/lsp_signature.nvim#56]
Hi there, thanks for the cool plugin!

I see empty lines in my signature for when the signature is only one line: 
<img width="410" alt="Screenshot 2021-08-02 at 16 02 05" src="https://user-images.githubusercontent.com/70747/127874063-25dccd95-e763-43f3-af50-cd88ab659361.png">

I have `doc_lines=0` and `max_height=3`

**Comment by ray-x** [comment]
It is strange, but I can not reproduce here.
I noticed that the signature is different. What LSP you are using? I doubt it sent an empty line....

![image](https://user-images.githubusercontent.com/1681295/128102220-f81b9c04-1e28-4b0b-a080-8503ca398c87.png)

**Comment by HansPinckaers** [comment]
Thanks for checking it @ray-x! I'm using jedi-language-server. How can I check it doesn't add a newline itself?

**Comment by ray-x** [comment]
It is jedi
The lsp response is : 

```lua
{
  documentation = {
    kind = "markdown",
    value = "```text\n\n```"
  },
  label = "system(command: _PathType) -> int",
  parameters = { {
      label = "command: _PathType"
    } }
}
```

They should send "```text\n```" instead. 
I add a workaround to remove that line, hope it would work for you.

Please also create an issue against jedi.
