### ISSUE TITLE
The popup doesn't disappear until I go back to normal mode.

### ISSUE THREAD

**Issue by 0xsamrath** [ray-x/lsp_signature.nvim#57]
https://user-images.githubusercontent.com/69572668/128047156-67bf3e76-c84a-4259-88a2-fa0640caf490.mov

**Comment by ray-x** [comment]
Added a bugfix for this issue. Please update the plugin and take a look. Thanks!

**Comment by samrath2007** [comment]
It works perfectly now! Thanks

**Comment by Willy-JL** [comment]
Sorry for necroposting but I still have this issue...

https://user-images.githubusercontent.com/49810075/141600436-d37e9133-b8cc-4190-849a-4c6ab298f8ab.mp4

I am using [NvChad](https://github.com/NvChad/NvChad) as the base of my configuration, but I made sure to disable all the custom config related to this plugin and the issue persists...

**Comment by ray-x** [comment]
A quick question. In the video @Willy-JL . Seems when the signature floating pop up, it changes from normal mode to insert mode. Not sure why would this happen.

**Comment by Willy-JL** [comment]
@ray-x I did that, the signature never pops up in normal mode, only in insert mode... and only if I enter insert mode while already between the brackets (or if I start typing the function from scratch in insert mode). Is that not how it's supposed to work?

**Comment by ray-x** [comment]
In normal mode, you can use whatever keymap you defined to `lua vim.lsp.buf.signature_help()` and it will show the signature. By default the keymap is <C-k>

**Comment by Willy-JL** [comment]
Alright thanks, but still shouldn't it go away after I exit the parentheses or I go to another line in insert mode?

**Comment by ray-x** [comment]
Yes, it should.

**Comment by ray-x** [comment]
It should be fixed.  Also, there is a setup option ` auto_close_after `
