### ISSUE TITLE
Popup comes up when going to next line in lua(outside a function parameter)

### ISSUE THREAD

**Issue by samrath2007** [ray-x/lsp_signature.nvim#58]
https://user-images.githubusercontent.com/69572668/128125267-7bac9683-a340-4557-aa77-488bcd6b9d53.mov

**Comment by ray-x** [comment]
Well. This is expected and a valid Lua grammar

suppose you have 
```lua
local helper = require 'you_module'
```
and 
```lua
local helper = require 'you_module'.helper
```
They are both valid

How about and a `\n` after  require 'you_module' like this:

```lua
local helper = require 'you_module'
.helper
```
This is the same as

```lua
local helper = require 'you_module'.helper
```
And all above are valid.

**Comment by samrath2007** [comment]
Is there a way into tricking the lua lsp into thinking otherwise?

**Comment by ray-x** [comment]
Frankly speaking, I do not know.

**Comment by samrath2007** [comment]
Ok, thanks
