### ISSUE TITLE
Feature request: option or callback to trigger the Saga Preview documentation

### ISSUE THREAD

**Issue by danielnehrig** [ray-x/lsp_signature.nvim#6]
Title

**Comment by ray-x** [comment]
I do not think there is an easy way to trigger Saga preview correctly.  Reason is the cursor is inside the function instead of on the function name.  And in some cases, the cursor might be on space or a function (as a parameter to another function).  So the request is more how to trigger a Saga preview when the cursor is not on the function name. To me, this is more a request to Saga instead of signature help.

**Comment by danielnehrig** [comment]
saga signature also works inside ()

**Comment by ray-x** [comment]
I think the best approach is this
register the lspsaga signature handler to the ['textDocument/signatureHelp"]. Currently,  the plugin checks if signature is registered or not and launch your registered lspsaga handler if registered

**Comment by danielnehrig** [comment]
alright i'll test that out

**Comment by zlksnk** [comment]
@danielnehrig has that worked out for you?

**Comment by danielnehrig** [comment]
nope

**Comment by ray-x** [comment]
I was a bit surprised that lspsaga does not register nor provide a public handler for signature. that is why the default configuration will fail. I have to call the lspsaga.signature() explicitly.

Please update to latest and use this config (sample with pyright):

```lua
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'glepnir/lspsaga.nvim'
Plug 'ray-x/lsp_signature.nvim'
call plug#end()
lua <<EOF

require'lspconfig'.pyright.setup {}
local saga = require 'lspsaga'
saga.init_lsp_saga()
require'lsp_signature'.on_attach({bind = false,  use_lspsaga=true})
EOF

```


![image](https://user-images.githubusercontent.com/1681295/118425568-c9ea5400-b70c-11eb-92c0-65afeb546bce.png)

**Comment by zlksnk** [comment]
@ray-x this doesn't highlights the function parameter that I'm typing. With `bind` set to true and `use_lspsaga` to false, `decorator` parameter works as intended but with lspsaga integration it doesn't. Would it be possible to implement this?

**Comment by andersevenrud** [comment]
@zlksnk neovim will support the parameter highlight natively at some point: https://github.com/neovim/neovim/pull/14456

So we'll probably see this in saga when it lands.
