### ISSUE TITLE
LSP signature shadow "behind" file/buffer normal text

### ISSUE THREAD

**Issue by rodhash** [ray-x/lsp_signature.nvim#60]
Hi

When using border = "shadow", this shadow keeps behind the normal file/buffer text, like this:

Normal code:
![image](https://user-images.githubusercontent.com/29671981/128267868-0e1c0a2a-e8b9-45be-91ea-1997cb4533a7.png)

And now with the shadow border "behind" the normal text:
![image](https://user-images.githubusercontent.com/29671981/128267904-489e6fbb-29d6-4c99-800a-7991e4e4b438.png)

Tried zindex = 200, higher and lower however no luck.

My gif recording is a mess so in case it helps recorded a quick video:
https://www.youtube.com/watch?v=VksejL1aoZg

Is this the expected behavior? I  can't make it "above" normal text.

Thanks.

**Comment by ray-x** [comment]
I think it is expected. The shadow option is more of an alpha channel. Even though it is on top of `rCount++` it does not prevent you from seeing it. It just cast a shadow on top of it. If you would like to block `rCount++` from been seen. Have to use options like `single` etc

**Comment by rodhash** [comment]
Oh I see .. alright thanks for the update. I really enjoyed this shadow option but sometimes things get weird when the code shows up, if at least the code was "faded" or highlighted in a gray tone/color I believe would be cool but couldn't find that highlight group.

Well, all good, really awesome plugin! Just switched to single, thanks a ton!

**Comment by ray-x** [comment]
Personally. I also prefer shadow and it was my default for a long time.
I will raise a ticket in neovim upstream later on.

**Comment by ray-x** [comment]
Wait.
I think you can try this option:

  "hi FloatShadow blend=80 guibg=Black",

The default value is 80, you can change blend value and guibg value and see how it looks.

Here is what it looks if you set it to 20
![image](https://user-images.githubusercontent.com/1681295/128277531-5a0fd092-7e7c-49a1-8172-774b7a579a8e.png)

**Comment by rodhash** [comment]
> Wait.
> I think you can try this option:
> 
> "hi FloatShadow blend=80 guibg=Black",
> 
> The default value is 80, you can change blend value and guibg value and see how it looks.
> 
> Here is what it looks if you set it to 20
> ![image](https://user-images.githubusercontent.com/1681295/128277531-5a0fd092-7e7c-49a1-8172-774b7a579a8e.png)

Awesome, worked great.. thanks again!
