### ISSUE TITLE
Get error after type: table.insert(

### ISSUE THREAD

**Issue by mks1508** [ray-x/lsp_signature.nvim#62]
After update.... everything ok except `table.insert(`

Error:
>Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1692: attempt to get length of a nil value

file: `/usr/share/nvim/runtime/lua/vim/lsp/util.lua` at line `1692`
```lua
--- Removes empty lines from the beginning and end.
--@param lines (table) list of lines to trim
--@returns (table) trimmed list of lines
function M.trim_empty_lines(lines)
  local start = 1
  for i = 1, #lines do
    if #lines[i] > 0 then       -- line 1692
      start = i
      break
    end
  end
  local finish = 1
  for i = #lines, 1, -1 do
    if #lines[i] > 0 then
      finish = i
      break
    end
  end
  return vim.list_extend({}, lines, start, finish)
end
```

neovim version: stable 0.5.0
lang-server: sumneko-lua 2.3.5

**Comment by ray-x** [comment]
What LSP you are using. Could you send a code snippet?

**Comment by mks1508** [comment]
I'm using builtin lsp with sumneko_lua.
After I update my plugins yesterday, everything still ok except typing `(` of `table.insert(` then get this error.

May be: problem from [Line 226](https://github.com/ray-x/lsp_signature.nvim/blob/04126aa17cbe863a4fe8ca43653cd9ef70f29c18/lua/lsp_signature.lua#L226)

I tried to capture value of `lines` before this line:
- with normal methods like `table.concat(` or `string.byte(`, output:
```lua
-- from table.concat(
{ "```lua", "function table.concat(list: table, sep?: string, i?: number, j?: number)", "```", "", "Given a list where all elements are strings or numbers, returns the string `list[i]..sep..list[i+1] ··· sep..list[j]`.", "", "[View documents](http://www.lua.org/manual/5.1/manual.html#pdf-table.concat)", "" }

-- from string.byte(
{ "```lua", "function string.byte(s: string, i?: number, j?: number)", "```", "", "Returns the internal numeric codes of the characters `s[i], s[i+1], ..., s[j]`.", "", "[View documents](http://www.lua.org/manual/5.1/manual.html#pdf-string.byte)", "" }
```
- but... with `table.insert(`, output:
```lua
{
  [0] = "function table.insert(list: table, value: any)",
  [2] = "```lua",
  [3] = "function table.insert(list: table, pos: number, value: any)",
  [4] = "```",
  [5] = "",
  [6] = "Inserts element `value` at position `pos` in `list`.",
  [7] = "",
  [8] = "[View documents](http://www.lua.org/manual/5.1/manual.html#pdf-table.insert)",
  [9] = "",
  [10] = "---"
}
```
The outputs of `table.insert(` and other methods seem different.

**Comment by ray-x** [comment]
Do you have document length setup `doc_lines` ?

**Comment by mks1508** [comment]
My config:
```lua
  require("lsp_signature").on_attach({
    hint_enable = false,
    handler_opts = {
      border = "single",
    },
    max_width = 80,
  })
```

**Comment by mks1508** [comment]
@ray-x
Actually, the problem is from `table.insert(` signature
```lua
{
  [0] = "function table.insert(list: table, value: any)",
  [2] = "```lua",
  [3] = "function table.insert(list: table, pos: number, value: any)",
  [4] = "```",
  [5] = "",
  [6] = "Inserts element `value` at position `pos` in `list`.",
  [7] = "",
  [8] = "[View documents](http://www.lua.org/manual/5.1/manual.html#pdf-table.insert)",
  [9] = "",
  [10] = "---"
}
```
It doesn't have any element at index 1 ... omg
`trim_empty_line` method from `vim.lsp.util`
```lua
...
  for i = 1, #lines do
    if #lines[i] > 0 then
...
```
That's why `table.insert(` have the problem

**Comment by mks1508** [comment]
The problem from this commit https://github.com/ray-x/lsp_signature.nvim/commit/ec496da95ed305f4831a9dfcf3a0b57c83c291e4

I tried to change `offset` from `0` to `1`
```lua
local offset = 1
```
The problem have gone

**Comment by ray-x** [comment]
Thanks. I pushed a new version.
The issue is caused by an incorrect markdown format. Offset 0 will insert content before markdown start delimiter  "```"

Issue should have been fixed.

**Comment by mks1508** [comment]
Thanks, the issue have been fixed.
But it has turned into another issue.

`table.insert` have two instances
![image](https://user-images.githubusercontent.com/42815562/128700646-254ae5d5-69e5-48ae-b0df-1aadf1cbb3aa.png)

when I type `(` ... It shows 2-args prototype above 3-args prototype
![image](https://user-images.githubusercontent.com/42815562/128700885-2d36461c-5b04-4b69-ad93-020527507d7f.png)

It seem ok until I try to type the third argument `table.insert(a, b,` ... then I got this error:
>Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:318: col value outside range

I tried to change `offset` from `2` to `3` and higher numbers
`local offset = 3` have best outcome
Now It shows 3-args prototype above 2-args prototype... and don't get any errors
![image](https://user-images.githubusercontent.com/42815562/128702702-4e1999ac-cd4d-4c7a-b7f4-33d6afce77b1.png)

**Comment by ray-x** [comment]
The root cause is sumneko does not provide the active signature. (activeSignature)
I added a workaround for this.

```lua
{
  signatures = { {
      activeParameter = 0,
      documentation = {
        kind = "markdown",
        value = "\nInserts element `value` at position `pos` in `list`.\n\n[View documents](http://www.lua.org/manual/5.1/manual.html#pdf-table.insert)\n\n---"
      },
      label = "function table.insert(list: table, pos: number, value: any)",
      parameters = { {
          label = { 22, 33 }
        }, {
          label = { 35, 46 }
        }, {
          label = { 48, 58 }
        } }
    }, {
      activeParameter = 0,
      documentation = {
        kind = "markdown",
        value = "\nInserts element `value` at position `pos` in `list`.\n\n[View documents](http://www.lua.org/manual/5.1/manual.html#pdf-table.insert)\n\n---"
      },
      label = "function table.insert(list: table, value: any)",
      parameters = { {
          label = { 22, 33 }
        }, {
          label = { 35, 45 }
        } }
    } }
}
```
