### ISSUE TITLE
svelteserver end_col value outside range

### ISSUE THREAD

**Issue by rudotriton** [ray-x/lsp_signature.nvim#63]
Writing a console log that has comma separated variables (`console.log(a,`) throws the following error:

`Error executing vim.schedule lua callback: ...pack/packer/opt/lsp_signature.nvim/lua/lsp_signature.lua:318: end_col value
 outside range`

**Comment by ray-x** [comment]
@rudotriton 
Could you enable the logs by setting and send me the logs:
```
  debug = false, -- set to true to enable debug logging
  log_path = "debug_log_file_path", -- debug log path

```
I tried to install svelteserver without luck.

I think this is a common failure from lsp server missing some of the fields required.

**Comment by rudotriton** [comment]
sure, here's the log:

<details>
  <summary>Log</summary>
<pre>
שׁ  |1: insert enter
שׁ  |1: insert enter
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: insert enter
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: / |2: / |3: /
שׁ  |1: insert enter
שׁ  |1: insert enter
שׁ  |1: newline, lets try signature
שׁ  |1: signature triggered
שׁ  |1: c |2: c |3: c
שׁ  |1: c |2: c |3: c
שׁ  |1: c |2: c |3: c
שׁ  |1: c |2: c |3: c
שׁ  |1: c |2: c |3: c
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: o |2: o |3: o
שׁ  |1: o |2: o |3: o
שׁ  |1: o |2: o |3: o
שׁ  |1: o |2: o |3: o
שׁ  |1: o |2: o |3: o
שׁ  |1: o |2: o |3: o
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: n |2: o |3: n
שׁ  |1: n |2: o |3: n
שׁ  |1: n |2: o |3: n
שׁ  |1: n |2: o |3: n
שׁ  |1: n |2: o |3: n
שׁ  |1: n |2: o |3: n
שׁ  |1: n |2: o |3: n
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: o |2: n |3: s
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: n |2: s |3: o
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: s |2: o |3: l
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: o |2: l |3: e
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: l |2: e |3: .
שׁ  |1: sig result
שׁ  |1: no result?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: e |2: . |3: l
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: . |2: l |3: o
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: l |2: o |3: g
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: signature triggered
שׁ  |1: sig result |2: {
  activeParameter = 0,
  activeSignature = 0,
  signatures = { {
      documentation = {
        kind = "markdown",
        value = "Prints to `stdout` with newline."
      },
      label = "log(message?: any, ...optionalParams: any[]): void",
      parameters = { {
          label = { 4, 17 }
        }, {
          label = { 19, 43 }
        } }
    }, {
      label = "log(...data: any[]): void",
      parameters = { {
          label = { 4, 18 }
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = "  console.log(",
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")" }
}

שׁ  |1: label: |2: log(message?: any, ...optionalParams: any[]): void |3: 0 |4: 1 |5: 0 |6: {
  documentation = {
    kind = "markdown",
    value = "Prints to `stdout` with newline."
  },
  label = "log(message?: any, ...optionalParams: any[]): void",
  parameters = { {
      label = { 4, 17 }
    }, {
      label = { 19, 43 }
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "CursorMoved", "CursorMovedI", "BufHidden", "InsertCharPre" },
  focus_id = "textDocument/signatureHelplsp_signature795",
  line_to_cursor = "  console.log(",
  max_height = 12,
  max_width = 120,
  offset_x = -4,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")" },
  zindex = 200
}

שׁ  |1: extmark |2: 5 |3: 17
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: signature triggered
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: ( |2: a |3: ,
שׁ  |1: signature triggered
שׁ  |1: sig result |2: {
  activeParameter = 0,
  activeSignature = 0,
  signatures = { {
      documentation = {
        kind = "markdown",
        value = "Prints to `stdout` with newline."
      },
      label = "log(message?: any, ...optionalParams: any[]): void",
      parameters = { {
          label = { 4, 17 }
        }, {
          label = { 19, 43 }
        } }
    }, {
      label = "log(...data: any[]): void",
      parameters = { {
          label = { 4, 18 }
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = "  console.log(a",
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")" }
}

שׁ  |1: label: |2: log(message?: any, ...optionalParams: any[]): void |3: 0 |4: 1 |5: 0 |6: {
  documentation = {
    kind = "markdown",
    value = "Prints to `stdout` with newline."
  },
  label = "log(message?: any, ...optionalParams: any[]): void",
  parameters = { {
      label = { 4, 17 }
    }, {
      label = { 19, 43 }
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "CursorMoved", "CursorMovedI", "BufHidden", "InsertCharPre" },
  focus_id = "textDocument/signatureHelplsp_signature699",
  line_to_cursor = "  console.log(a",
  max_height = 12,
  max_width = 120,
  offset_x = -4,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")" },
  zindex = 200
}

שׁ  |1: sig_cfg bufnr, winnr not valid |2: 5 |3: 1002
שׁ  |1: extmark |2: 5 |3: 17
שׁ  |1: sig result |2: {
  activeParameter = 1,
  activeSignature = 0,
  signatures = { {
      documentation = {
        kind = "markdown",
        value = "Prints to `stdout` with newline."
      },
      label = "log(message?: any, ...optionalParams: any[]): void",
      parameters = { {
          label = { 4, 17 }
        }, {
          label = { 19, 43 }
        } }
    }, {
      label = "log(...data: any[]): void",
      parameters = { {
          label = { 4, 18 }
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = "  console.log(a,",
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")" }
}

שׁ  |1: label: |2: log(message?: any, ...optionalParams: any[]): void |3: 0 |4: 1 |5: 1 |6: {
  documentation = {
    kind = "markdown",
    value = "Prints to `stdout` with newline."
  },
  label = "log(message?: any, ...optionalParams: any[]): void",
  parameters = { {
      label = { 4, 17 }
    }, {
      label = { 19, 43 }
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "CursorMoved", "CursorMovedI", "BufHidden", "InsertCharPre" },
  focus_id = "textDocument/signatureHelplsp_signature591",
  line_to_cursor = "  console.log(a,",
  max_height = 12,
  max_width = 120,
  offset_x = -4,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", ",", "<", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")", ")" },
  zindex = 200
}

שׁ  |1: bufnr, ns |2: 6 |3: 17
שׁ  |1: last para |2: { "CursorMoved", "CursorMovedI", "BufHidden", "InsertCharPre" }

שׁ  |1: extmark |2: 20 |3: 43
שׁ  |1: completedone  |2: i |3: enable signature ?
</pre>
</details>

**Comment by ray-x** [comment]
It is strange.
I managed to installed sevlte today. Still failed to reproduce issue you saw.
The log looks different
```
{
  activeParameter = 0,
  activeSignature = 0,
  signatures = { {
      label = "log(...data: any[]): void",
      parameters = { {
          label = { 4, 18 }
        } }
    } }
}
```
For me, `log` function only has 1 signature `log(...data: any[]): void`, from your log, you have other one `log(message?: any, ...optionalParams: any[]): void`


Could you check if you still saw the issue in latest code.
Also what is the version of sevlte you are using?

**Comment by rudotriton** [comment]
I noticed it would also happen with `print` in lua.

The latest changes have fixed it. So thank you very much 🙌

**Comment by mortezadadgar** [comment]
I faced this issue today with gopls and gorilla/mux 

<details>
<summary>Log</summary>
<pre>
שׁ  |1: insert enter
שׁ  |1: insert enter
שׁ  |1: newline, lets try signature
שׁ  |1: g |2: g |3: g
שׁ  |1: g |2: g |3: g
שׁ  |1: e |2: e |3: e
שׁ  |1: e |2: e |3: e
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: t |2: e |3: t
שׁ  |1: t |2: e |3: t
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: t |2: e |3: t
שׁ  |1: t |2: e |3: t
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: e |2: t |3: :
שׁ  |1: e |2: t |3: :
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: t |2: : |3: =
שׁ  |1: t |2: : |3: =
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: t |2: : |3: =
שׁ  |1: t |2: : |3: =
שׁ  |1: : |2: = |3: s
שׁ  |1: : |2: = |3: s
שׁ  |1: = |2: s |3: m
שׁ  |1: = |2: s |3: m
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: s |2: m |3: .
שׁ  |1: s |2: m |3: .
שׁ  |1: m |2: . |3: h
שׁ  |1: m |2: . |3: h
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: . |2: h |3: a
שׁ  |1: . |2: h |3: a
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: u |2: n |3: c
שׁ  |1: u |2: n |3: c
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: signature triggered
שׁ  |1: sig result |2: {
  activeParameter = 0,
  activeSignature = 0,
  signatures = { {
      documentation = "HandleFunc registers a new route with a matcher for the URL path.\nSee Route.Path() and Route.HandlerFunc().\n",
      label = "HandleFunc(path string, f func(http.ResponseWriter,\n\t*http.Request)) *mux.Route",
      parameters = { {
          label = "path string"
        }, {
          label = "f func(http.ResponseWriter,\n\t*http.Request)"
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = "\tget := sm.HandleFunc(",
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", "," }
}

שׁ  |1: label: |2: HandleFunc(path string, f func(http.ResponseWriter,
	*http.Request)) *mux.Route |3: 0 |4: 1 |5: 0 |6: {
  documentation = "HandleFunc registers a new route with a matcher for the URL path.\nSee Route.Path() and Route.HandlerFunc().\n",
  label = "HandleFunc(path string, f func(http.ResponseWriter,\n\t*http.Request)) *mux.Route",
  parameters = { {
      label = "path string"
    }, {
      label = "f func(http.ResponseWriter,\n\t*http.Request)"
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "BufHidden", "InsertLeavePre" },
  focus_id = "textDocument/signatureHelplsp_signature795",
  line_to_cursor = "\tget := sm.HandleFunc(",
  max_height = 12,
  max_width = 120,
  offset_x = -11,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", "," },
  zindex = 200
}

שׁ  |1: extmark |2: 12 |3: 22 |4: 0
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: signature triggered
שׁ  |1: sig result
שׁ  |1: no result?
שׁ  |1: ( |2: " |3: /
שׁ  |1: ( |2: " |3: /
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: completedone  |2: i |3: enable signature ?
שׁ  |1: / |2: " |3: ,
שׁ  |1: signature triggered
שׁ  |1: sig result |2: {
  activeParameter = 1,
  activeSignature = 0,
  signatures = { {
      documentation = "HandleFunc registers a new route with a matcher for the URL path.\nSee Route.Path() and Route.HandlerFunc().\n",
      label = "HandleFunc(path string, f func(http.ResponseWriter,\n\t*http.Request)) *mux.Route",
      parameters = { {
          label = "path string"
        }, {
          label = "f func(http.ResponseWriter,\n\t*http.Request)"
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = '\tget := sm.HandleFunc("/",',
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", "," }
}

שׁ  |1: label: |2: HandleFunc(path string, f func(http.ResponseWriter,
	*http.Request)) *mux.Route |3: 0 |4: 1 |5: 1 |6: {
  documentation = "HandleFunc registers a new route with a matcher for the URL path.\nSee Route.Path() and Route.HandlerFunc().\n",
  label = "HandleFunc(path string, f func(http.ResponseWriter,\n\t*http.Request)) *mux.Route",
  parameters = { {
      label = "path string"
    }, {
      label = "f func(http.ResponseWriter,\n\t*http.Request)"
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "BufHidden", "InsertLeavePre" },
  focus_id = "textDocument/signatureHelplsp_signature699",
  line_to_cursor = '\tget := sm.HandleFunc("/",',
  max_height = 12,
  max_width = 120,
  offset_x = -11,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", "," },
  zindex = 200
}

שׁ  |1: bufnr, ns |2: 18 |3: 10
שׁ  |1: last para |2: { "CursorMoved", "CursorMovedI", "BufHidden", "InsertCharPre" }

שׁ  |1: extmark |2: 25 |3: 67 |4: 0
שׁ  |1: / |2: " |3: ,
שׁ  |1: signature triggered
שׁ  |1: sig result |2: {
  activeParameter = 1,
  activeSignature = 0,
  signatures = { {
      documentation = "HandleFunc registers a new route with a matcher for the URL path.\nSee Route.Path() and Route.HandlerFunc().\n",
      label = "HandleFunc(path string, f func(http.ResponseWriter,\n\t*http.Request)) *mux.Route",
      parameters = { {
          label = "path string"
        }, {
          label = "f func(http.ResponseWriter,\n\t*http.Request)"
        } }
    } }
}
 |3: {
  border = "single",
  check_client_handlers = true,
  check_pumvisible = true,
  line_to_cursor = '\tget := sm.HandleFunc("/", ',
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", "," }
}

שׁ  |1: label: |2: HandleFunc(path string, f func(http.ResponseWriter,
	*http.Request)) *mux.Route |3: 0 |4: 1 |5: 1 |6: {
  documentation = "HandleFunc registers a new route with a matcher for the URL path.\nSee Route.Path() and Route.HandlerFunc().\n",
  label = "HandleFunc(path string, f func(http.ResponseWriter,\n\t*http.Request)) *mux.Route",
  parameters = { {
      label = "path string"
    }, {
      label = "f func(http.ResponseWriter,\n\t*http.Request)"
    } }
}

שׁ  |1: win config |2: {
  border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
  check_client_handlers = true,
  check_pumvisible = true,
  close_events = { "BufHidden", "InsertLeavePre" },
  focus_id = "textDocument/signatureHelplsp_signature591",
  line_to_cursor = '\tget := sm.HandleFunc("/", ',
  max_height = 12,
  max_width = 120,
  offset_x = -11,
  stylize_markdown = true,
  trigger_from_lsp_sig = true,
  triggered_chars = { "(", "," },
  zindex = 200
}

שׁ  |1: sig_cfg bufnr, winnr not valid |2: 18 |3: 1003
שׁ  |1: last para |2: { "CursorMoved", "CursorMovedI", "BufHidden", "InsertCharPre" }

שׁ  |1: extmark |2: 25 |3: 67 |4: 0
</pre>
</details>

**Comment by mortezadadgar** [comment]
@ray-x I'm still facing this issue look 
![image](https://user-images.githubusercontent.com/27911493/131866845-44688f14-2810-40f7-a6b1-e69ad475ec27.png)

**Comment by ray-x** [comment]
@mortezadadgar 
Thanks, it should been fixed.

**Comment by axieax** [comment]
I noticed this happening for my Java projects, prominent in long/nested function calls
