### ISSUE TITLE
the latest commit causes errors in `c` 

### ISSUE THREAD

**Issue by abzcoding** [ray-x/lsp_signature.nvim#64]
the changes in [this](https://github.com/ray-x/lsp_signature.nvim/commit/0381f3cb17f46c5e7a7277bb267d8f594da17430) commit, causes nil value error on `activeParameter` field

![err](https://user-images.githubusercontent.com/10992695/128740481-f31bcc84-813b-4cd1-bc20-ad6ebd7a89ad.gif)

![Screen Shot 2021-08-09 at 8 56 31 PM](https://user-images.githubusercontent.com/10992695/128740528-d7a5b12d-5773-457f-9616-6cb6d65aed07.jpg)

```vim
echom &filetype
```
will return `c`

and
```vim
:LspInfo
```
is returning the following
<img width="1701" alt="Screen Shot 2021-08-09 at 8 59 21 PM" src="https://user-images.githubusercontent.com/10992695/128740800-906b20eb-9465-4308-9ade-33f5f22e5953.png">

also it was working just fine before this commit

**Comment by Pocco81** [comment]
Yep, it will happen with every language server except from the sumneko lua one. I proposed a fix on #65.

**Comment by ray-x** [comment]
Thanks for head up. This issue should be fixed in the latest version.

**Comment by abzcoding** [comment]
thanks mate, the issue is fixed
