### ISSUE TITLE
`Error executing vim.schedule lua callback: .../lua/lsp_signature.lua:151: attempt to perform arithmethic on field 'activeParameter' (a nil value))`

### ISSUE THREAD

**Issue by Pocco81** [ray-x/lsp_signature.nvim#65]
Getting this error on Golang code:

![image](https://user-images.githubusercontent.com/58336662/128739492-53c138ed-f10e-49f9-a3f2-c681640269e0.png)

But everything works fine on lua tho. I assume this is due to improper handling of that setting for every other lang sever without that setting. It looks like it came from the commit 0381f3c. This will fix it:

```lua
  for i = #result.signatures, 1, -1 do
    sig = result.signatures[i]
    if (sig.activeParameter ~= nil) then -- this
      if sig.activeParameter + 1 > #sig.parameters then
        table.remove(result.signatures, i)
      end
    end -- this
  end
```

(it's a very simple fix, so I don't think a PR is needed)

**Comment by ray-x** [comment]
Thanks. Should has been fixed in latest version.

**Comment by Pocco81** [comment]
Yep, it works now. Keep up the good work! Btw @ray-x, is there a way to see the doc floating window only when you first enter the `()` and then just use the virtual text thing?

![image](https://user-images.githubusercontent.com/58336662/128742376-26f7e876-1c99-4dac-8a44-54494ae773b1.png)

**Comment by ray-x** [comment]
Cheers!
Regarding your question, it will need an extra flag.
An alternative way is disable floatwindow, and trigger lsp.buf.signature_help() when you want to see the floating window ( for me I bind  <M-K> to  lsp.buf.signature_help() in insert mode)

**Comment by Pocco81** [comment]
Also, #66 is related to this issue as well.
