### ISSUE TITLE
Error with functions that have no parameters: `lsp_signature.lua:151: attempt to get length of field 'parameters' (a nil value)`

### ISSUE THREAD

**Issue by Pocco81** [ray-x/lsp_signature.nvim#66]
https://user-images.githubusercontent.com/58336662/128745699-c93f232e-2c56-4b1f-814f-204ef697f969.mp4

I presume this is being caused by the recent commits as well. This wasn't happening before, but still, I'll grab older commits to see whether this is happening or not.

Edit: everything works fine on this commit: 4f9fadffe1dea21cd465f5acbf00f702fca5580b, thought I'd let you know.

**Comment by Pocco81** [comment]
This has relation with #65.

**Comment by ray-x** [comment]
This one should have been fixed
