### ISSUE TITLE
LUA error "attempt to get length of a nil value" when trying to show signature for console.* in JS/TS files

### ISSUE THREAD

**Issue by hood** [ray-x/lsp_signature.nvim#67]
Just as the title says, I'm getting constant errors when console.log/dir/debug/etc.. signature definitions are supposed to be displayed.

[Here](https://i.imgur.com/K4dQo5z.png) a screenshot if the error.
[Here](https://i.imgur.com/S8t5jS7.png) a screenshot of the line where the error gets thrown.

**Comment by ray-x** [comment]
hi, @hood 
Would you check if you still saw the issue? I have some code update yesterday and one may be related to this.

**Comment by hood** [comment]
I'm trying to get a PR merged into neovim's repo that should avoid this issue altogether, but in the meantime I'll update your plugin and let you know if your fix works.

**Comment by hood** [comment]
Ok, just tested the behaviour and it looks like your latest changes fixed the issue. Congrats!
