### ISSUE TITLE
compe completions popup appears on top of the signature popup

### ISSUE THREAD

**Issue by Gelio** [ray-x/lsp_signature.nvim#7]
Hey, I appreciate the work put into this plugin :+1: 

I have begun experimenting with it and I have noticed that the `compe` completions popup appears on top of the signature popup, both are shown at the same time:
![image](https://user-images.githubusercontent.com/889383/116248981-a1ee7d00-a76c-11eb-9e3b-885666e8f33f.png)

In the gif shown in https://www.reddit.com/r/neovim/comments/mzjxhq/lsp_signature_can_be_better/ the signature popup is hidden when the completions popup is shown. Is there something else I need to configure?

I have only followed the readme instructions. I am calling `require'lsp_signature'.on_attach()` inside the LSP's `on_attach` function for a given lsp config.

**Comment by ray-x** [comment]
Hi, I did some code update (check if popup existed or not). Does the new version fix the issue?

**Comment by Gelio** [comment]
Thanks! Yes, it does seem to work better now :+1:

**Comment by horseinthesky** [comment]
There are still some issues with this.

If I have tabnine compe source enabled compe overlaps lsp_signature.
```
require'compe'.setup {
  preselect = 'disable',
  source_timeout = 100,

  source = {
    path = {kind = ""},
    buffer = {kind = ""},
    calc = {kind = ""},
    nvim_lsp = {kind = ""},
    nvim_lua = {kind = ""},
    spell = {kind = ""},
    ultisnips = {kind = ""},
    tabnine = {kind = "", priority = 50},
    emoji = {kind = "ﲃ", filetypes={"markdown"}},
  },
}

utils.map('i', '<CR>', 'compe#confirm("<CR>")', {expr = true})

local on_attach = function(client, _)
  require "lsp_signature".on_attach()
  <some other stuff>
end

lspconfig.jedi_language_server.setup {
  on_attach = on_attach
}
```

![image](https://user-images.githubusercontent.com/19948672/116775557-2fcbb000-aa6c-11eb-8bdd-b58afbe09d3b.png)

**Comment by ray-x** [comment]
This is caused by tablenine is slow and it is shown after signature popup.  The timing is hard to control and won't be fixed.

**Comment by andersevenrud** [comment]
Sorry to disturb a closed issue, but maybe this new neovim nightly feature could help prevent this ?

https://github.com/neovim/neovim/pull/14468

**Comment by ray-x** [comment]
Looks interesting. Thanks for the head up. This is a very useful API changes.
But unfortunately,  signature relay on nvim focusable_preview API to display the hint messages( instead of on floating window API directly)
So will need to change focusable_preview API so z-index can be supported.
