### ISSUE TITLE
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:153: attempt to get length of field 'parameters' (a nil value)

### ISSUE THREAD

**Issue by AllenDang** [ray-x/lsp_signature.nvim#70]
I checked the existing issue list, found simular issues marked fixed, after update to newest version, issue remains on my side.

It happened in method without any param, filetype is golang.

Here is the error message
```
Error executing vim.schedule lua callback: ...ck/packer/start/lsp_signature.nvim/lua/lsp_signature.lua:153: attempt to get length of field 'parameters' (a nil value)
```

**Comment by ray-x** [comment]
What lsp you are using?
Also would be good to send a code snippet when you saw this error.

**Comment by AllenDang** [comment]
I'm using gopls.

![commatolines](https://user-images.githubusercontent.com/18550/128983636-4e43d33b-57d0-45ca-803e-6804cd03a470.gif)

**Comment by ray-x** [comment]
What is gopls version and what is the signature of Update() look like?

**Comment by AllenDang** [comment]
@ray-x g.Update() is a method without any param.
```
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
```

**Comment by ray-x** [comment]
I pushed an update for it.
I am using gopls 0.7.1. Not sure if it is relevant.

**Comment by AllenDang** [comment]
@ray-x It is fixed. Thanks!
