### ISSUE TITLE
Python signature highlighting throws error

### ISSUE THREAD

**Issue by jsappl** [ray-x/lsp_signature.nvim#71]
I'm having issues with signature highlighting for even simple Python functions like, e.g., `range`. If I start typing the window pops up after the first parantheses `(` and shows the signatures correctly:
![Screenshot from 2021-08-11 21-44-55](https://user-images.githubusercontent.com/10909765/129093730-6f6f2eda-3a5e-4f0f-bf6e-f865104bbc5a.png)

However, highlighting on the fly when entering the `range` function arguments breaks things:
![Screenshot from 2021-08-11 21-45-24](https://user-images.githubusercontent.com/10909765/129093823-a634f930-7cf0-4912-ac14-a51e44db5496.png)

```
Error executing vim.schedule lua callback: ...pack/paqs/start/lsp_signature.nvim/lua/lsp_signature.lua:201: attempt to index a nil value
```

Btw thanks for the plugin, it's a nice addition to the `nvim-compe` plugin. Oh, and it's working perfectly well for `golang` with `gopls`.

**Comment by ray-x** [comment]
The signature label looks strange. Double checked and seems pyright is not giving activeSignature.

I add a workaround to this issue.
