### ISSUE TITLE
NgConfigValues is a nil value

### ISSUE THREAD

**Issue by Gelio** [ray-x/lsp_signature.nvim#73]
After the latest update (https://github.com/ray-x/lsp_signature.nvim/commit/a7d1817403b12ab574bee46e70864ceaf82707d9), I'm getting the following error when the signature would be shown:

```
Error executing vim.schedule lua callback: ...er/start/lsp_signature.nvim/lua/lsp_signature_helper.lua:173: attempt to index global '_NgConfigValues' (a nil value)
```

I'm using rather a vanilla configuration:

```lua
	use("ray-x/lsp_signature.nvim")
```

and attaching the following way:

```lua
	require("lsp_signature").on_attach({
		zindex = 50, -- signature should appear below compe completions
	})
```

**Comment by chaeing** [comment]
Same here.
Works fine with the previous commit 91d6747e2451c51d4ffa4ec4a093f986eef78b55

**Comment by AllenDang** [comment]
Same here.

**Comment by Gelio** [comment]
Seems to be fixed by https://github.com/ray-x/lsp_signature.nvim/commit/1c4a686e05ef30e4b815d1e3d77507f15efa7e99.

The problem does not appear for me after updating and I can see the signature again. Thanks @ray-x

**Comment by ray-x** [comment]
Thanks for confirming. Sorry for using the wrong global variable.

**Comment by Gelio** [comment]
No worries, happens to the best of us. Thanks for a quick fix!
