### ISSUE TITLE
Disable window for jsx/tsx

### ISSUE THREAD

**Issue by MasterGordon** [ray-x/lsp_signature.nvim#75]
Is there a way to disable the signature in jsx/tsx parts of files, in this parts of the file the signature is just sadly just annoying.
![image](https://user-images.githubusercontent.com/18127395/129461761-a5f58d1a-3a07-4927-be96-7473cb9466d8.png)

**Comment by ray-x** [comment]
You can set `trigger_on_newline = false`
It does not prevent signature inside jsx. But it will stop popup when you in new line.

**Comment by ray-x** [comment]
Please use the following setup:
```lua
    require"lsp_signature".setup({
      toggle_key = [[<M-x>]],
    })
```
If you press \<M-x> will toggle signature window. Also `trigger_on_newline = false` should help.
