### ISSUE TITLE
Feature Requst: Allow toggling hide and show in insert mode without moving cursor

### ISSUE THREAD

**Issue by zeertzjq** [ray-x/lsp_signature.nvim#77]
The floating window covers some visible code, and currently the only way I can find to hide the floating window without moving cursor is switching to normal mode. Is it possible to allow toggling hide and show in insert mode, or to expose a Lua function to toggle hide and show?

**Comment by ray-x** [comment]
Added a new setup for this:
```
toggle_key = nil -- toggle signature on and off in insert mode,  e.g. toggle_key = '<M-x>'
```

**Comment by zeertzjq** [comment]
The floating window seems to lose its border after being toggled off, then on.

**Comment by ray-x** [comment]
Yes. need to pass the setup in as well.
