### ISSUE TITLE
Shows signature after close bracket on newline in rust

### ISSUE THREAD

**Issue by J-E-Mc** [ray-x/lsp_signature.nvim#80]
Typing a function call and not terminating it with a semicolon causes the signature popup to show on the next line
Example:
```rust
fn test() {}

fn main() {
    test()
    // signature will still show up when typing on this line
}
```

https://user-images.githubusercontent.com/44543806/131566447-82771da8-8268-45f9-bccd-9918156123c9.mp4

**Comment by ray-x** [comment]
Fixed
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1681295/178637556-5b4daf8b-d0e8-4d71-8758-70a90aaebfec.png">
