### ISSUE TITLE
Error in startup

### ISSUE THREAD

**Issue by zsinx6** [ray-x/lsp_signature.nvim#82]
I'm having the following error with the latest version:

`[dein] Vim(lua):E5108: Error executing....lua:398: '=' expected near 'continue'`

Can you help me?

**Comment by ray-x** [comment]
A bit strange...  I think it crash on `goto continue` statement...
Are you using nvim 0.5+  ?

**Comment by zsinx6** [comment]
> Are you using nvim 0.5+ ?

Yes

**Comment by ray-x** [comment]
Could you send a vimrc I can reproduce?

**Comment by zsinx6** [comment]
I'm using the config from here: https://github.com/rafi/vim-config
No errors in the checkhealth (only perl, but always was that way without problems)

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/131780823-221edc77-ad59-40b8-a300-e1821e27dca5.png)
I did a fresh install of vim-config. Can not reproduce.

**Comment by zsinx6** [comment]
Is it possible to generate some kind of log to know what is going on with my system?

**Comment by ray-x** [comment]
It may be related to your operating system and lua version.  Maybe you can try to update the neovim to latest one.
Signature also has log available. But as your plugin crashed when startup. I am not sure it can help. But you can check and set
```
      log_path = vim.fn.expand("$HOME") .. "/tmp/sig.log",
      debug = true,
```
And check if there are something in sig.log

**Comment by zsinx6** [comment]
Nothing in the log, I recompiled neovim and lua, tried luajit as well, but without success. Also tried a fresh install from the vim-config.
Another information that can be useful, the python LSP also didn't work, maybe the root cause can be the same?

**Comment by ray-x** [comment]
lsp signature does require related language server start and work correctly. 
Did you install with :LspInstall python ?

**Comment by zsinx6** [comment]
> Did you install with :LspInstall python ?

Yes, but when I check the LspInfo there is no one running, in the past few days, I remember seeing 2 running there

**Comment by zsinx6** [comment]
I just finished recompiling lua+neovim, using luajit and wihtout lua52 compatibility, and now it works! I guess the lua is not supported and needs to be only `luajit`.

**Comment by ray-x** [comment]
Great! As far as I know, juajit is different to lua52.  Also goto statement may different in lua51, luajit and lua52
