### ISSUE TITLE
Don't fix pos if the client does not support activeParameter

### ISSUE THREAD

**Issue by akinsho** [ray-x/lsp_signature.nvim#84]
Hi @ray-x,

This slightly relates to #22. Basically I would like to have the `fix_pos` option enabled for languages that support this functionality i.e. the provide an `activeParameter` in the case of `dart` it doesn't and since it has `named parameters` etc. it doesn't close automatically when `fix_pos` is true but I would like this to work for other languages.

I know that I can use the `attach` function to check the client name for dart and change the option dynamically but I want to keep my lsp-signature config separate from lsp config by using a `setup`  function not `on_attach`. I know this is a personal preference but is there anyway that `fix_pos` can default to being off if the lsp for that language won't handle it well?

**Comment by ray-x** [comment]
You could bind ` toggle_key = <M-x>` to turn off signature windows. Does it help?
A feature only for lsp which does not support activeParameter ( e.g dartls) will look wired...

**Comment by akinsho** [comment]
@ray-x I was thinking less of making an exception for dart which would be weird but more that the `fix_pos` functionality shouldn't ever really apply to *any* lsp that doesn't have what it needs to work so it's sort of a check within the plugin if the minimum criteria for fix_pos are present otherwise the functionality isn't enabled. Tbh I've just moved to using an `on_attach` and excluding clients that way 🤷🏿‍♂️ so this is fully up to you. If it sounds like more trouble than it's worth I'm happy to close this out.

**Comment by ray-x** [comment]
I will allow `fix_pos` to be a function
Please check the README on how to setup.

**Comment by akinsho** [comment]
@ray-x thanks for adding this 👍🏿 I've been using it but am now getting quite confusing behaviour where the window doesn't seem to close even in languages that support it like `sumneko_lua`. 
My config is
```lua
    use {
      'ray-x/lsp_signature.nvim',
      config = function()
        require('lsp_signature').setup {
          bind = true,
          fix_pos = function(signatures, _) -- second argument is the client
            return signatures[1].activeParameter >= 0 and signatures[1].parameters > 1
          end,
          hint_enable = false,
          handler_opts = {
            border = 'rounded',
          },
        }
      end,
    }
```

**Comment by akinsho** [comment]
Seems like this is going to be fix in terraform ls so will close this here
