### ISSUE TITLE
Typing argument of function changes title of window

### ISSUE THREAD

**Issue by reisnobre** [ray-x/lsp_signature.nvim#87]
I'm using lsp_signature on my projects and it has an anyoing behaviour that changes the window title on each keystroke or something like this.
I'm able to suppress this behaviour by setting the option `set notitle`.

Video showing the behaviour below. It would be useful to have this behaviour removed or to have an option to suppress it.

https://user-images.githubusercontent.com/12832066/132046707-ee4528e9-ee2e-47e2-91ac-4ac161c83991.mov

As you can see, it flickers.

**Comment by ray-x** [comment]
title / notitle is global variable. By default it is `notitle` on neovim startup

**Comment by reisnobre** [comment]
I'm talking about suppressing the behavior where the plug-in changes the title of the screen. 
Not setting the notitle option  on neovim.

Sorry for the confusion.

**Comment by ray-x** [comment]
If `title` is true, vim will automatically get the title of the signature floating window when popup. It is not plugin behaviour.

**Comment by reisnobre** [comment]
Because the plug-in counts as a new window, so when the focus change the title changes? Makes sense. 

Is this the same behavior when using saga to display windows?

**Comment by ray-x** [comment]
Yes.
I do not use gui-nvim. So I can not see this behaviour.
What make things worse for lsp_signature is that the floating window will refresh/recreate itself when you type. This will cause `title` to flick.

**Comment by reisnobre** [comment]
I'm not using GUI-vim, just neovim, this should be happening then?

**Comment by ray-x** [comment]
I am using terminal + galaxy-line/windline both do not show behaviour like this.
`title` is by default to be `false`.  Is it been set somewhere in your vimrc?

**Comment by reisnobre** [comment]
I'm using Lunarvim, so it might have been. But I'll do a double check.

**Comment by reisnobre** [comment]
Yeah, the title comes on true by default, I disabled and it's better for now. 
Maybe there's a way to avoid changing focus to the window created by lsp_signature to have both of two worlds? If it's not possible or maybe not worthy we can close this issue.

**Comment by reisnobre** [comment]
Fixed, thank you very much @ray-x 😄.
I'll study and learn how your plugin work so I'm able to help a bit more in the future. The option `focusable` worked like a charm.
