### ISSUE TITLE
"binding 3rd signature will be deprecated" is not very clear

### ISSUE THREAD

**Issue by IndianBoy42** [ray-x/lsp_signature.nvim#89]
Since updating today I have seen this message popup in the cmdline window below a few times. Firstly, it took a while to find that this was the plugin printing it. Now I gather its to do with the breaking changes neovim is considering for lsp handlers in 0.6. However im still not sure if there is a config/fix that I should be applying to get rid of this message for now. What is `check_client_handlers`?

What is the feature that is being deprecated here?

**Comment by siduck76** [comment]
I get this issue too : 

![image](https://user-images.githubusercontent.com/59060246/132118430-858c52e1-cfe0-4ea0-85a5-22b0239e1cda.png)

**Comment by ray-x** [comment]
The plugin will disable hook signature handler from other sources. E.g. from lspsaga signature.

**Comment by siduck76** [comment]
I dont use lspsaga

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/132122308-3b63f166-0dc1-4d67-a838-83f452a21cd0.png)

another error message

**Comment by ray-x** [comment]
Is your plugin updated? I pushed a few commits today.

**Comment by siduck76** [comment]
thanks! it works now :)
