### ISSUE TITLE
Use a highlight instead of backtick for formatting the current parameter

### ISSUE THREAD

**Issue by mpasa** [ray-x/lsp_signature.nvim#9]
First of all, thank you for this plugin, I think it's very useful I think that some parts of how we display the current parameter can be improved. My case is the following:

- Functions with 1 parameter don't show backticks or any special color for the first and unique parameter (and thus, the current one)
- Functions with more than 1 parameter show correctly with backticks. In my case, though, only the backticks themselves have a different color. The parameter name itself appears with the same color as the rest of the text. My markdown inline code blocks have the correct color, so not sure which file format it's getting to show it. I'm trying it with Rust and rust-analyzer LSP.

My proposal will be, if possible, to add a highlight to them, instead of adding the backticks. By default, it can be linked to some other like `Keyword`, or have a default color provided by the plugin.

**Comment by ray-x** [comment]
Thanks for the suggestion. 
The highlight is hard... The reason behind this is that markdown is used in the preview window. The support of markdown colour is bad...  Nvim does not support markdown colour syntax (HTML syntax). That why in the end I am using tick for the colouring. Why neovim choose markdown? I think might relate to display the comments in a nice way.
I will leave the issue open for now as neovim still refactor this their preview code. I would hope they come up with something better.

**Comment by ray-x** [comment]
By using the new api from neovim, I solve this issue in the last commits. would you check the behaviour?
