### ISSUE TITLE
Lsp-signature prefix does not goes away

### ISSUE THREAD

**Issue by imSafdarAwan** [ray-x/lsp_signature.nvim#94]
![Screenshot_2021-09-05_16-39-38](https://user-images.githubusercontent.com/87114084/132129904-d1a0692f-9830-4179-8a21-911983184d62.png)

**Comment by kristijanhusak** [comment]
This also happens to me randomly, but also the signature popup is visible. I'm here in normal mode, cursor is just not visible on screenshot:

![screenshot](https://i.imgur.com/3SHF6qZ.png)

I'm just not sure how to reproduce it 100%.

Some additional info:
* Completion: nvim-cmp
* OS: Linux
* Neovim version: NVIM v0.6.0-dev+218-g3f526feeb

**Comment by kmescharikov** [comment]
+

**Comment by ray-x** [comment]
I would suspect it is a issue that InsertLeave event was not trigger/missed. But not sure is it a defect from neovim or from the plugin.  I am working on code cleanup this week. And will back to this once I finished.

**Comment by naripok** [comment]
> This also happens to me randomly, but also the signature popup is visible

This happens to me (every time) whenever I open a function parenthesis and leave insert mode before the signature popup shows.
The pop will get stuck and the only two ways to close it is to enter insert mode again inside the parenthesis and exit or to call `lua vim.lsp.buf.signature_help()`.
I'm also using `nvim-cmp` and `lspconfig`.
Please, let me know if I can help with more info for debugging or anything else, really. :)

**Comment by ErikReider** [comment]
I've noticed this too... When `pasting a method in insert mode`  ->  `move cursor to end of method parenthesis`  ->  `^C`  ->  `:w`.

**Comment by danielgatis** [comment]
same here! :(

**Comment by ray-x** [comment]
I did not see this happen for a while. I am using `gopls`, `tsserver` and `pyright`
Please check if it goes away by disabling autopair plugins or any similar plugins (or, maybe check my setup ray-x/nvim regarding how to setup autopir). 
Please post your language server, your function signature and your lsp_signature config.
Also, a walk around is define the toggle key to toggle the floating window.

**Comment by imSafdarAwan** [comment]
sorry i found what was causing it if you use <c-c> (ctrl+c) to get out of the insert mode then use <c-[> this thing wont happen again 
and also if ctrl+c is you habbit then set inoremap <C-c> <NOP>

**Comment by shlomocarmeter** [comment]
Had the same problem. Setting inoremap <C-c> to <esc> fixed this for me. Thanks @imSafdarAwan!

**Comment by ray-x** [comment]
`<ctrl-c>` will trigger `InsertLeave` event on which signature is hooked on. So the plugin has no idea you are not in Normal mode and should close the popup.

**Comment by andriati-alex** [comment]
Thanks guys I really liked the plugin and was facing the same problem exiting with `<ctrl-c>`

**Comment by ray-x** [comment]
Sorry. I was doing some refactor in last few days.
Pushed a change to master. Hope it works.

**Comment by druskus20** [comment]
It seems to work! Thanks!
