### ISSUE TITLE
Error: attempt to index field 'documentation' (a nil value)

### ISSUE THREAD

**Issue by spindensity** [ray-x/lsp_signature.nvim#95]
# Steps to reproduce

Use `sumneko_lua` language server, enter `insert` mode, try to change any parameters on the 4th line of the following `lua` code.

```lua
function common_on_attach(client, bufnr)
    local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
    local opts = { noremap = true, silent = true }
    buf_set_keymap("n", "<localleader>gl", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opts)
end
```

# Expected behavior

No errors occur, we can change the parameters as desired.

# Actual behavior

The plugin raises the error:
![Snipaste_2021-09-07_20-57-43](https://user-images.githubusercontent.com/33576822/132348668-8006a8f0-6083-4710-ae35-95263eee1b7e.png)

**Comment by ray-x** [comment]
Would you check if the issue still there?

**Comment by spindensity** [comment]
> Would you check if the issue still there?

The fix has solved the problem, thanks.
