### ISSUE TITLE
Option to be hidden defaultly

### ISSUE THREAD

**Issue by acomagu** [ray-x/lsp_signature.nvim#99]
Can I disable the auto-popup? I want it be shown only when I hit `toggle_key`.

Thanks! :heart:

**Comment by ray-x** [comment]
You can set `floating_window=false`

**Comment by acomagu** [comment]
@ray-x Can I show popup by hitting `toggle_key`?(specifying that seems to disable `toggle_key` also...)

**Comment by ray-x** [comment]
Yes, you can. Alternatively, you can show popup with your keybinding to vim.lsp.buf.signature_help()

**Comment by acomagu** [comment]
vim.lsp.buf.signature_help() works! Thanks.
